### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by BuyMyMojo** [nowrep/obs-vkcapture#1]
Error only happen when running `make && make install`

`/home/buymymojo/obs-vkcapture/src/vkcapture.c:20:10: fatal error: obs-nix-platform.h: No such file or directory
   20 | #include <obs-nix-platform.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/linux-vkcapture.dir/build.make:82: CMakeFiles/linux-vkcapture.dir/src/vkcapture.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:124: CMakeFiles/linux-vkcapture.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
[buymymojo@buymymojo build]$ 
`

**Comment by alosarjos** [comment]
Can you provide more info on your distribution/system?

I just compiled and tried it on Arch Linux and it's working perfectly

**Comment by BuyMyMojo** [comment]
![Screenshot_2021-03-23_01-21-30](https://user-images.githubusercontent.com/46948241/112004720-25b5b800-8b76-11eb-8512-47fd4da354e9.png)

**Comment by alosarjos** [comment]
Looks to me that you have the wrong version of OBS installed on your system. The one with EGL support provides the file

**Comment by nowrep** [comment]
Yes, you need to build against current git version of obs-studio.

From readme:

    Requires OBS with EGL support (currently unreleased, you need to build from git).
