### ISSUE TITLE
vkcapture on Solus OS

### ISSUE THREAD

**Issue by ghost** [nowrep/obs-vkcapture#100]
There have been a few reddit posts asking about this, but I'm looking to package GameCapture into Solus, which is sort of notorious for being difficult to package for. As far as I know this is only easily doable on Solus by using the Flatpak version of Steam and OBS, which isn't exactly ideal.
What would be ideal would for it to be in the Solus repos, a simple eopkg install obs-vkcapture, but the package request I began months ago hasn't had much activity. What would it take to build this myself on Solus? Can it be installed as any other regular OBS plugin, from the source tarball?

**Comment by nowrep** [comment]
I have absolutely no idea what you are asking.
It can be installed as any other OBS plugin.
