### ISSUE TITLE
Include lib32-obs-vkcapture-git in the github page

### ISSUE THREAD

**Issue by AmyRoxwell** [nowrep/obs-vkcapture#102]
I use an Arch based distro and I didnt knew that you needed lib32-obs-vkcapture-git to make 32 bits native linux games (like TF2) to work with vkcapture, so maybe add it as a sidenote below the AUR vkcapture link so less people forget to install it if they need it.

**Comment by Tsubajashi** [comment]
a little sidenote how to build the 32bit library for that would be cool, too - for everyone that doesnt use arch! :)

**Comment by nowrep** [comment]
It will differ, but should be mostly the same as on arch:

https://github.com/nowrep/obs-vkcapture/blob/480a8d95e2a3008d26c4509f05231d5c3f6cde0b/dist/PKGBUILD#L26-L36
