### ISSUE TITLE
No games are being captured

### ISSUE THREAD

**Issue by pmartiner** [nowrep/obs-vkcapture#107]
### Description
unfortunately none of my games are being captured by OBS after reinstalling mi OS. 
the games and OBS do seem to detect the plugin (i'm using `OBS_VKCAPTURE=1` as an env variable). so far i've tried 4 games and none of them were detected.

PS: i'm using the AUR [obs-vkcapture](https://aur.archlinux.org/packages/obs-vkcapture) package

### System specs:
```
[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          6.0.7-arch1-1
Desktop:         GNOME
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 5600X 6-Core Processor
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             31.3 GB
Swap:            4.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 5500 XT (navi14, LLVM 14.0.6, DRM 3.48, 6.0.7-arch1-1)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 22.2.2
OpenGL Core:     4.6 (Core Profile) Mesa 22.2.2
OpenGL ES:       OpenGL ES 3.2 Mesa 22.2.2
Vulkan:          Supported
```

### Logs:
[OBS logs](https://pastebin.com/raw/XDBMhjux)
[Apex Legends logs](https://github.com/nowrep/obs-vkcapture/files/9977894/steam-1172470.log)
[Hades logs](https://github.com/nowrep/obs-vkcapture/files/9977896/steam-1145360.log)
[Fall Guys logs](https://github.com/nowrep/obs-vkcapture/files/9977904/steam-1097150.log)

**Comment by nowrep** [comment]
Can you try with `OBS_VKCAPTURE_LINEAR=1 OBS_VKCAPTURE=1`?

**Comment by pmartiner** [comment]
exporting `OBS_VKCAPTURE_LINEAR=1` did it! thanks @nowrep
