### ISSUE TITLE
Doesn't work with Lutris and LoL

### ISSUE THREAD

**Issue by freebirb** [nowrep/obs-vkcapture#108]
I am certainly sure the problem is me, but I do simply not understand what to do, I guess. Could we add some Wiki or more detailed docs, for not so smart non-devs, like me ?

Scenario: League of Legends installed through Lutris. MANGOHUD runs flawlessly, game capture does not. It's not pick-able as game source. Neither the League client, nor the League game.

Running an AMD RX 6900 XT on Arch Linux with GNOME on Wayland. Installed OBS with vkcapture like [this](https://github.com/obsproject/obs-studio/pull/7206#issuecomment-1286434550). Capturing the rotating cube does work.

I tried following things:

1. Add `OBS_VKCAPTURE` set to `1` to `Settings -> System Options -> Environment variables`. Game launches, but is not pick-able as game source.
2. Add `obs-gamecapture` set to `1` to `Settings -> System Options -> Environment variables`. Game launches, but is not pick-able as game source.
3.  Add `OBS_VKCAPTURE=1` to `Settings->System Options->Command prefix`
4.  Add `obs-gamecapture` to `Settings->System Options->Command prefix`. Game launches, but is not pick-able as game source.

No clue what to do. I guess I simply don't understand how this works at all. Help appreciated. Once I got this figured, I'm willing to contribute to a wiki or something.

**Comment by nowrep** [comment]
`OBS_VKCAPTURE` is environment variable, `obs-gamecapture` is command.

`env OBS_VKCAPTURE=1` as command prefix should work.
Also please post logs from both OBS and the game (lutris).

**Comment by freebirb** [comment]
Reinstalled the OS (because of other reasons). Works now, I don't know what the issue was before.

Thanks for your plugin.
