### ISSUE TITLE
Cannot capture Red Dead Redemption 2

### ISSUE THREAD

**Issue by DomiStyle** [nowrep/obs-vkcapture#111]
Not sure if I'm doing something wrong but I can't get obs-vkcapture to capture Red Dead Redemption 2 via Vulkan.

I tried Doom Eternal, which also uses Vulkan in Proton and it captures with no issues but with Red Dead Redemption 2 the screen will just stay black in OBS.

Here is the Proton log with debugging enabled: 
[steam-1174180.log](https://github.com/nowrep/obs-vkcapture/files/10114848/steam-1174180.log)

Any ideas? This is the only game I have issues with.

**Comment by nowrep** [comment]
Can you try with current `master`?

**Comment by DomiStyle** [comment]
Ah yes, master seems to fix the issue. Thanks!
Unfortunately 1.2.0 is the latest available in Nobara but I will keep using my own build for now.

Quick question, I assume I have to build the 32-bit version as well since i only have a `obs_vkcapture_64.json` in my implicit layers now. What would be the correct cmake command for that?

**Comment by nowrep** [comment]
If you want to use it with 32bit software, then yes. Look at nobara packaging to see how to make a 32bit build.
