### ISSUE TITLE
Not capturing games running through Lutris on Nobara

### ISSUE THREAD

**Issue by Faugus** [nowrep/obs-vkcapture#113]
Setting "obs-gamecapture" in command prefix doesn't work.
I tried on Manjaro and openSUSE and it's working.
On Nobara, if I run the game through console using obs-gamecapture wine, it works.

**Comment by nowrep** [comment]
So it works on Manjaro/openSUSE and yet you didn't think of reporting this to Nobara instead?

Last time someone had issues on Nobara it turned out they have outdated package, so try to build from git instead.
