### ISSUE TITLE
[Feature Request] FFMPEG support

### ISSUE THREAD

**Issue by jrsmile** [nowrep/obs-vkcapture#115]
Hi, would it be possible to have a binary that spits out the capture like "vk-play | ffmpeg -i pipe:" to prevent the overhead to use obs?

**Comment by nowrep** [comment]
It would be possible, but it's out of scope here.
Also if overhead is your concern, it would be more complicated than just piping to ffmpeg.

**Comment by hashworks** [comment]
Has this changed in any way? I would also be interested in a ffmpeg input from obs-vkcapture.
