### ISSUE TITLE
Game Capture Mostly Working with Windowed mode

### ISSUE THREAD

**Issue by FaddishDisc7** [nowrep/obs-vkcapture#12]
After testing for a while with game capture on steam linux native games and proton games, I noticed that most of the recordings stutter heavily on fullscreen mode , but not on windowed mode ingame. Is it meant to only work with windowed mode?

**Comment by nowrep** [comment]
No, it shouldn't matter if you have the game in fullscreen or window.

**Comment by FaddishDisc7** [comment]
Oh ok , I guess I have to tinker more on my obs settings.

**Comment by nowrep** [comment]
You can at least post your setup then: what GPU you have, what game you are trying to capture, what is the fps of the game, what fps you have configured in OBS, ...
