### ISSUE TITLE
Game Capture as source not available on Wayland only, on X11 it works fine

### ISSUE THREAD

**Issue by Faugus** [nowrep/obs-vkcapture#123]
`[faugus@faugus-linux ~]$ obs
debug: Found portal inhibitor
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/locale.ini
Attempted path: /usr/share/obs/obs-studio/locale.ini
Attempted path: share/obs/obs-studio/themes/Yami.qss
Attempted path: /usr/share/obs/obs-studio/themes/Yami.qss
info: Platform: Wayland
info: CPU Name: AMD Ryzen 5 5600X 6-Core Processor
info: CPU Speed: 4619.272MHz
info: Physical Cores: 6, Logical Cores: 12
info: Physical Memory: 15903MB Total, 1557MB Free
info: Kernel Version: Linux 6.0.13-201.fsync.fc36.x86_64
info: Distribution: "Nobara Linux" 36
info: Session Type: wayland
info: Qt Version: 6.3.1 (runtime), 6.3.1 (compiled)
info: Portable mode: false
Attempted path: share/obs/obs-studio/themes/Dark/no_sources.svg
Attempted path: /usr/share/obs/obs-studio/themes/Dark/no_sources.svg
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_tbar_position_valueChanged(int)
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_actionShowTransitionProperties_triggered()
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_actionHideTransitionProperties_triggered()
info: OBS 28.1.2 (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
        samples per sec: 48000
        speakers:        2
        max buffering:   960 milliseconds
        buffering type:  dynamically increasing
info: ---------------------------------
info: Initializing OpenGL...
info: Using EGL/Wayland
info: Initialized EGL 1.5
info: Loading up OpenGL on adapter AMD AMD Radeon RX 6800 XT (navi21, LLVM 14.0.5, DRM 3.48, 6.0.13-201.fsync.fc36.x86_64)
info: OpenGL loaded successfully, version 4.6 (Core Profile) Mesa 22.3.0, shading language 4.60
info: ---------------------------------
info: video settings reset:
        base resolution:   2560x1440
        output resolution: 2560x1440
        downscale filter:  Bicubic
        fps:               120/1
        format:            NV12
        YUV mode:          Rec. 709/Partial
info: NV12 texture support not available
info: P010 texture support not available
info: Audio monitoring device:
        name: Default
        id: default
info: ---------------------------------
warning: No AJA devices found, skipping loading AJA UI plugin
warning: Failed to initialize module 'aja-output-ui.so'
warning: No AJA devices found, skipping loading AJA plugin
warning: Failed to initialize module 'aja.so'
warning: Failed to load 'en-US' text for module: 'decklink-captions.so'
warning: Failed to load 'en-US' text for module: 'decklink-output-ui.so'
libDeckLinkAPI.so: cannot open shared object file: No such file or directory
warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
warning: Failed to initialize module 'decklink.so'
info: [pipewire] Available captures:
info: [pipewire]     - Desktop capture
info: [pipewire]     - Window capture
warning: v4l2loopback not installed, virtual camera disabled
error: [linux-vkcapture] linux-vkcapture cannot run on non-EGL platforms
warning: Failed to initialize module 'linux-vkcapture.so'
info: [obs-browser]: Version 2.18.7
info: [obs-browser]: CEF Version 103.0.5060.134 (runtime), 103.0.0-5060-shared-textures_143.2591+g4204d54+chromium-103.0.5060.134 (compiled)
info: NVENC supported
info: [obs-ndi] [obs_module_load] Hello! (Plugin Version: 5.0.0 | Linked NDI Version: 5.0.10)
info: [obs-ndi] [load_ndilib] Trying library path: '/usr/lib64'
info: [obs-ndi] [load_ndilib] Found NDI library file at '/usr/lib64/libndi.so.5'
info: [obs-ndi] [load_ndilib] NDI runtime loaded successfully.
info: [obs-ndi] [obs_module_load] Loaded NDIlib binary.
info: [obs-ndi] [obs_module_load] Initialized NDIlib.
info: [obs-ndi] [restart_ndi_finder] Created NDI finder.
info: [obs-ndi] [obs_module_load] NDI runtime finished loading. Version: NDI SDK LINUX 10:20:36 Oct 19 2022 5.5.2
info: [obs-ndi] [ndi_output::ndi_output] NDI 5 Output created.
info: [obs-ndi] [ndi_output::ndi_output] NDI 5 Output created.
info: [obs-ndi] [obs_module_load] Finished loading.
info: [obs-vaapi] version: undefined, gst-runtime: 1.20.3
error: [obs-vaapi] vapostproc element not found
warning: Failed to initialize module 'obs-vaapi.so'
info: [obs-websocket] [obs_module_load] you can haz websockets (Version: 5.0.1 | RPC Version: 1)
info: [obs-websocket] [obs_module_load] Qt version (compile-time): 6.3.1 | Qt version (run-time): 6.3.1
info: [obs-websocket] [obs_module_load] Linked ASIO Version: 101201
info: [obs-websocket] [obs_module_load] Module loaded.
info: [Source Record] loaded version 0.3.1
error: os_dlopen(libvlc.so.5->libvlc.so.5): libvlc.so.5: cannot open shared object file: No such file or directory

info: [vlc-video]: Couldn't find VLC installation, VLC video source disabled
info: ---------------------------------
info:   Loaded Modules:
info:     vlc-video.so
info:     text-freetype2.so
info:     source-record.so
info:     rtmp-services.so
info:     obs-x264.so
info:     obs-websocket.so
info:     obs-vst.so
info:     obs-transitions.so
info:     obs-outputs.so
info:     obs-ndi.so
info:     obs-filters.so
info:     obs-ffmpeg.so
info:     obs-browser.so
info:     linux-v4l2.so
info:     linux-pulseaudio.so
info:     linux-pipewire.so
info:     linux-capture.so
info:     linux-alsa.so
info:     image-source.so
info:     frontend-tools.so
info:     decklink-output-ui.so
info:     decklink-captions.so
info: ---------------------------------
info: ==== Startup complete ===============================================
error: Encoder ID 'h265_texture_amf' not found
info: All scene data cleared
info: ------------------------------------------------
info: pulse-input: Server name: 'PulseAudio (on PipeWire 0.3.61) 15.0.0'
info: pulse-input: Audio format: s16le, 48000 Hz, 2 channels
info: pulse-input: Started recording from 'alsa_output.usb-Kingston_HyperX_Cloud_II_Wireless_000000000001-00.analog-stereo.monitor' (default)
info: [Loaded global audio device]: 'Desktop Audio'
info: pulse-input: Server name: 'PulseAudio (on PipeWire 0.3.61) 15.0.0'
info: pulse-input: Audio format: s16le, 48000 Hz, 1 channels
info: pulse-input: Started recording from 'alsa_input.usb-Kingston_HyperX_Cloud_II_Wireless_000000000001-00.mono-fallback' (default)
info: [Loaded global audio device]: 'Mic/Aux'
info: Switched to scene 'Scene'
info: ------------------------------------------------
info: Loaded scenes:
info: - scene 'Scene':
info: ------------------------------------------------
Attempted path: share/obs/obs-studio/images/overflow.png
Attempted path: /usr/share/obs/obs-studio/images/overflow.png
info: adding 21 milliseconds of audio buffering, total audio buffering is now 21 milliseconds (source: Desktop Audio)`

**Comment by nowrep** [comment]
You need to build this obs-vkcapture with wayland support (check the wayland dependencies).
