### ISSUE TITLE
problem with vkbasalt and capture

### ISSUE THREAD

**Issue by mesmerx** [nowrep/obs-vkcapture#125]
when i am trying to use vkbasalt and the capture i am getting this
 
![Screenshot 2022-12-26 19-22-40](https://user-images.githubusercontent.com/16441524/209586309-d4195c17-9a4a-44bc-aa6f-08a7efb6f33b.png)

 even if no reshader is being used or the vkb is turn off, if i remove the VKB enable its back to normal
 
 the normal:
![Screenshot 2022-12-26 19-15-19](https://user-images.githubusercontent.com/16441524/209586330-02897e43-524c-4541-a43d-1e59bf385bf4.png)

**Comment by nowrep** [comment]
Is this with master? What GPU do you have?

**Comment by mesmerx** [comment]
oh sorry
it`s with master using the git aur package for archlinux

**Comment by mesmerx** [comment]
i closed this by a missclick sorry haha

**Comment by nowrep** [comment]
Can you try reverting last commit? 4b7a50e

**Comment by mesmerx** [comment]
i`ll try and return about that

**Comment by mesmerx** [comment]
same with thee 1.2.2

**Comment by mesmerx** [comment]
i tried the 2.1 and 2.0 same result

**Comment by nowrep** [comment]
Does it happen with every game (including `vkcube`) or just with the battle.net launcher?

**Comment by mesmerx** [comment]
it happens at least in battle net + overwatch, i'll try another games today and return here

**Comment by mesmerx** [comment]
oh....  it only happens in battle net and games launched by it ....

**Comment by mesmerx** [comment]
strange......... in the game itself now its working as indented.... so i think i`ll close this , thx for the help :)

**Comment by mesmerx** [comment]
for anyoone with this problem what i did was teh same as https://github.com/nowrep/obs-vkcapture/issues/14
` cp  ~/.config/vkBasalt/vkBasalt.conf  ~/.local/share/vulkan/explicit_layer.d/`
then 
`VK_ADD_LAYER_PATH=/usr/share/vulkan/implicit_layer.d:$HOME/.local/share/vulkan/implicit_layer.d VK_LOADER_LAYERS_ENABLE="VK_LAYER_OBS_vkcapture_*"  ENABLE_VKBASALT=1 __GL_DXVK_OPTIMIZATIONS=1 __GL_SHADER_DISK_CACHE=1 __GL_SHADER_DISK_CACHE_PATH="/home/mesmer/Overwatch" DXVK_ASYNC=1 mesa_glthread=true DXVK_CONFIG_FILE="/home/mesmer/Overwatch/dxvk.conf" DXVK_STATE_CACHE_PATH="/home/mesmer/Overwatch"  obs-gamecapture mangohud %command%`
in steam fixes the problem

**Comment by mesmerx** [comment]
and i want to say thanks for all this work @nowrep  i am using a lot of your projects and plugins right now including the amd encoder for obs, seriously you are a angel
