### ISSUE TITLE
Can't launch games with obs-gamecapture %command%

### ISSUE THREAD

**Issue by arnogon** [nowrep/obs-vkcapture#130]
SteamOS 3.4.4 on Steam Deck.
Installed OBS, OBS plugin and capture tools from Flathub. OBS now shows 'Game Capture', but games don't launch when I put obs-gamecapture %command% in the launch options.

**Comment by nowrep** [comment]
https://github.com/nowrep/obs-vkcapture#about-flatpak

**Comment by arnogon** [comment]
Okay. I have since built obs-gamecapture and put it somewhere in PATH. Now games do launch in desktop mode (with obs-gamecapture %command%), but OBS game capture still can't see them; and I still can't launch games with the launch options.

**Comment by arnogon** [comment]
Okay. I have since built obs-gamecapture and put it somewhere in PATH. Now games do launch in desktop mode (with obs-gamecapture %command%), but OBS game capture still can't see them; and I still can't launch games with the launch options in game mode.

**Comment by nowrep** [comment]
Please post logs from both OBS and the game itself.

**Comment by arnogon** [comment]
[2023-01-10 21-26-41.txt](https://github.com/nowrep/obs-vkcapture/files/10383202/2023-01-10.21-26-41.txt)
Where can I find the log for a game?

**Comment by arnogon** [comment]
[2023-01-10 23-14-26.txt](https://github.com/nowrep/obs-vkcapture/files/10384018/2023-01-10.23-14-26.txt)
[steam-637650.log](https://github.com/nowrep/obs-vkcapture/files/10384024/steam-637650.log)
In game mode the game doesn't launch and there's no Steam log. These are the logs when tested in desktop mode.

**Comment by nowrep** [comment]
I don't see the game being launched with capture enabled at all in the log.
`env OBS_VKCAPTURE=1 %command%` please see README.

**Comment by nowrep** [comment]
`Command: ['/run/media/mmcblk0p1/steamapps/common/FINAL FANTASY XV/ffxv_s.exe']`

**Comment by arnogon** [comment]
> You are not running the game with capture enabled:
> `Command: ['/run/media/mmcblk0p1/steamapps/common/FINAL FANTASY XV/ffxv_s.exe']`

I’m afraid I don’t understand. Should I change the launch options?

**Comment by nowrep** [comment]
Try with `env VK_LOADER_DEBUG=all OBS_VKCAPTURE=1 PROTON_LOG=1 %command%`, it will show why it's not loading vkcapture.

**Comment by arnogon** [comment]
[steam-637650.log](https://github.com/nowrep/obs-vkcapture/files/10390060/steam-637650.log)
In Gaming Mode with `env VK_LOADER_DEBUG=all OBS_VKCAPTURE=1 PROTON_LOG=1 %command%`.

**Comment by nowrep** [comment]
Are you using flatpak steam?
Also please just test with vkcube first `OBS_VKCAPTURE=1 vkcube`.

**Comment by arnogon** [comment]
> Are you using flatpak steam? Also please just test with vkcube first `OBS_VKCAPTURE=1 vkcube`.

No not Flatpak, it's just the built-in Steam.
[2023-01-11 17-05-34.txt](https://github.com/nowrep/obs-vkcapture/files/10390537/2023-01-11.17-05-34.txt)
Testing in Desktop Mode.

**Comment by nowrep** [comment]
Please post output of `VK_LOADER_DEBUG=all OBS_VKCAPTURE=1 vkcube`

**Comment by arnogon** [comment]
[vkcube.log](https://github.com/nowrep/obs-vkcapture/files/10390954/vkcube.log)
Tested in Gaming Mode.

**Comment by nowrep** [comment]
Alright so it's back to my first reply https://github.com/nowrep/obs-vkcapture/issues/130#issuecomment-1375609155

> For capturing games outside Flatpak runtime, you need native build regardless of if you are using Flatpak OBS or not.

If you are on steam deck you should be able to just install `obs-vkcapture-git` from AUR.

**Comment by arnogon** [comment]
> Alright so it's back to my first reply [#130 (comment)](https://github.com/nowrep/obs-vkcapture/issues/130#issuecomment-1375609155)
> 
> > For capturing games outside Flatpak runtime, you need native build regardless of if you are using Flatpak OBS or not.
> 
> If you are on steam deck you should be able to just install `obs-vkcapture-git` from AUR.

As mentioned I'm now used my own build, so this shouldn't be a problem.

However I just found another problem: `PATH` in Gaming Mode is different from that in Desktop Mode so my `obs-gamecapture` wasn't actually there. With that fixed this is the new log.
[vkcube.log](https://github.com/nowrep/obs-vkcapture/files/10391125/vkcube.log)
Does that make a difference?

Also I'm aware that I could install it from AUR, but root partition in SteamOS is read-only and I'd rather not break the seal.

**Comment by nowrep** [comment]
You also need to move the layer json to a path where the vulkan loader will find it.
Just install it from AUR.

**Comment by arnogon** [comment]
Okay, moved the json file to the corresponding path, now OBS recognizes the program and has the correct dimensions for it. But the screen is still black.
Here are the logs:
[2023-01-11 19-51-24.txt](https://github.com/nowrep/obs-vkcapture/files/10391990/2023-01-11.19-51-24.txt)
[vkcube.log](https://github.com/nowrep/obs-vkcapture/files/10391992/vkcube.log)

**Comment by nowrep** [comment]
Same issue as #127 - try adding `OBS_VKCAPTURE_LINEAR=1`.

**Comment by arnogon** [comment]
Thanks, now it works with some games.
But for other games, OBS is still not picking the window.
[2023-01-11 20-33-09.txt](https://github.com/nowrep/obs-vkcapture/files/10392372/2023-01-11.20-33-09.txt)
This particular game isn't run through Proton so `PROTON_LOG=1` doesn't seem to generate log.

**Comment by arnogon** [comment]
How do I tell if a game is Vulkan or OpenGL?
Also I ran it with `obs-gamecapture` too, but OBS didn’t see that either.

**Comment by arnogon** [comment]
[portal2.log](https://github.com/nowrep/obs-vkcapture/files/10399983/portal2.log)
Managed to get the log. I think Portal 2 is Vulkan.

**Comment by nowrep** [comment]
You also need to install 32bit vkcapture.

**Comment by arnogon** [comment]
Is that something I can get from Flathub or should it be in my build as well?

**Comment by nowrep** [comment]
You need to build it yourself.

**Comment by arnogon** [comment]
I have now built obs_vkcapture_32.json, but don’t I need the 32-bit version of libVkLayer_obs_vkcapture.so as well? Right now I only have the 64-bit version and it’s provided by the Flatpak. I don’t think there’s a i386 version of the plugin on Flathub though.
