### ISSUE TITLE
`OBS_USE_EGL` is unneeded in OBS 28.0.0 and newer

### ISSUE THREAD

**Issue by Tachi107** [nowrep/obs-vkcapture#131]
Starting with commit https://github.com/obsproject/obs-studio/commit/ca2d02c2ce5278e7403e0d343ca743cb91fd068f, OBS Studio dropped the GLX renderer and, as far as I can tell, uses EGL everywhere.

I think that the readme should be updated to mention it.

**Comment by Tachi107** [comment]
Thanks! A bit off topic, but I'm curious. Why doesn't OBS itself ship this efficient capture method by default? Have you looked into upstreaming this?

**Comment by nowrep** [comment]
> Have you looked into upstreaming this?

No, and I'm pretty sure they wouldn't accept it because it needs external configuration (need to start the game in a special way, it doesn't "just work").

**Comment by Tachi107** [comment]
Il giorno mar 17 gen 2023 alle 04:45:17 -08:00:00, David Rosca 
***@***.***> ha scritto:
> No, and I'm pretty sure they wouldn't accept it because it needs 
> external configuration

Fair enough. Thanks for your work :)
