### ISSUE TITLE
Not so  much as an  issue but a request

### ISSUE THREAD

**Issue by nekoRunya** [nowrep/obs-vkcapture#134]
First of all, I apologise for posting this on the Issues list. I am new to github and actually only made an account for this req.
I have noticed that it is possible to capture two different applications with gamecapture. 

However, if one of the applications close, the source that was capturing the app that just closed will switch to capturing the last remaining application, often resulting in two sources capturing the same thing.

I was wondering if it is possible to isolate a source so that only one of the sources is allowed to capture a specific application. I myself have an application running at all times during my stream that would benefit greatly from gamecapture. However I cannot use it with gamecapture if I want to also  capture my games, since if I decide to switch the game for example, my application will get duplicated on my obs and will have to manually switch windows once the game had launched.

An interesting way that I had thought about might be where we can 'save' the application in the list, perhaps by checking a box. Then we can select either the saved application, regardless of if it is running or not, or select a blank one that will capture whatever other application that runs with gamecapture. 

Another way, and  possibly easier to code? Idk I couldn't tell.... But perhaps we can  add an  argument to group the application that runs with gamecapture, being able to select which group the source is allowed to capture? THat way it will  only show the apps in that group, the default being 0 or 1 for example...

Regardless, thank you for your time in reading this wall of text, and I hope you have a great day!

**Comment by nowrep** [comment]
Did you actually change the "window" to capture in properties? If you set it to specific window, it will only capture that one instead of the default behavior which is capturing *any* available window.

**Comment by nekoRunya** [comment]
Again, my problem is not that. What I want is for the one set to capture any window to exclude a certain gamecapture window. To try and explain better, I have application x that I am capturing with source 1. I want source 2 to capture my other games while excluding application x. Currently, source 2 captures application x when another application, let's call it y stops. I want to exclude application x from source 2's range of capture.

**Comment by nowrep** [comment]
In that case I can do either:

* prefer choosing a window that isn't already displayed in other game capture instance
* add "ignore" list what windows not to capture

**Comment by nekoRunya** [comment]
Oh, actually, an ignore list would be perfect

**Comment by nekoRunya** [comment]
also sorry for replying so late, I don't really use github so I kind of forgot I had an acc
