### ISSUE TITLE
Dota 2 crashes immediately from Game Capture

### ISSUE THREAD

**Issue by ghost** [nowrep/obs-vkcapture#137]
Dota 2 crashes the moment the Game Capture source is added.

https://user-images.githubusercontent.com/127980027/225388680-392f5f4a-abdc-4f9a-95cf-da8b3a22066d.mp4

When launching Steam through the terminal and then trying to launch the game, this outputs in the terminal repeatedly (literally hundreds of times nonstop) until the game crashes:

```
This can be expected when replaying an archive from Steam.
If replaying just the application cache, make sure to replay together with the common cache, as application cache can depend on common cache.
Fossilize ERROR: Failed to parse pNext chain for sType: 1000320002
Fossilize WARN: Referenced Pipeline layout 073622f199889dda, but it does not exist.
```

When I remove the Game Capture source, Dota 2 runs fine.

**Comment by nowrep** [comment]
Can you get a backtrace?
