### ISSUE TITLE
Is there someway to know if obs-vkcapture is running?

### ISSUE THREAD

**Issue by sifiro** [nowrep/obs-vkcapture#140]
Hi!, I usually use OBS Replay Buffer always-on and Advanced Scene Switch to switch scenes automatically using as reference: cursor position, process existence, file existence, window focus and other ways.

I would like to know or request If obs-vkcapture makes or someway is making noticeable when It's recording some game or Vulkan application. (for example, making a file in /run or /tmp )

**Comment by nowrep** [comment]
There will be dmabufs you can list with `ls -l /proc/$(pidof obs)/fd`.

**Comment by nowrep** [comment]
So you just want to know when there are clients (games) connected to OBS waiting for capture to start?

Client connect:

https://github.com/nowrep/obs-vkcapture/blob/eadcf2666608743ca497e2ef10761bcc6bb64959/src/vkcapture.c#L741-L750

Client disconnect:

https://github.com/nowrep/obs-vkcapture/blob/eadcf2666608743ca497e2ef10761bcc6bb64959/src/vkcapture.c#L674-L680

You can add your code there (check `server.clients.num` to see if there is any client connected).
