### ISSUE TITLE
Running obs on xwayland does not capture game (Nvidia)

### ISSUE THREAD

**Issue by Tesla-Tank** [nowrep/obs-vkcapture#141]
Sorry for starting a new thread but I'm having a different issue and couldn't report it earlier. I used the command `obs -platform xcb` but when I tried to select a game to capture it would print out:

`error: Cannot create EGLImage: One or more argument values are invalid.
warning: [linux-vkcapture] Asking client to create texture no modifiers`

I tried this on a x11 session and wayland session which both worked but not on xwayland. I also manually built it to the latest version 1.3.1 and used the preinstalled version of it (nobara's gamecapture) nothing worked. Tested it with aoe2, rotmg and vkcube, no captures on xwayland. Any suggestions to fix this? I appreciate your help with this, thank you.

Pastebin OBS:
https://paste.gloriouseggroll.tv/?61bdbfc883792953#GAZVp9bJcRKCNQ656HNKocw41DyHme447KDoN2DonqM3

Pastebin vkcube:
https://paste.gloriouseggroll.tv/?95d3c5abe60957ba#D5i2ugZqRZpbSF95dE5VdzF2Rre6ocAXMdZfUe41GUV6

Nobara37 
KDE 5.27.3
nvidia: 530.41.03

**Comment by nowrep** [comment]
Your OBS is running on llvmpipe (software OpenGL). Fix your nvidia driver install and it will work.

**Comment by Tesla-Tank** [comment]
> Your OBS is running on llvmpipe (software OpenGL). Fix your nvidia driver install and it will work.

I'm assuming this does work on nvidia with xwayland?  I've asked the creator of Nobara GloriousEggroll about this and he wasn't sure what was causing the issue. The distro has a wizard to download the drivers. Thank you

**Comment by nowrep** [comment]
> I'm assuming this does work on nvidia with xwayland? 

I can't tell you as I don't have nvidia card. Maybe they just don't support EGL on XWayland, it would be weird but I guess it wouldn't actually break much since most legacy X11 apps run on GLX anyway.

Why do you need to run OBS on XWayland?
