### ISSUE TITLE
Add an option to enable Overlays capture

### ISSUE THREAD

**Issue by Faugus** [nowrep/obs-vkcapture#144]
OBS doesn't capture MangoHud while using obs-gamecapture.
A workaround for this is set `VK_ADD_LAYER_PATH=/usr/share/vulkan/implicit_layer.d VK_LOADER_LAYERS_ENABLE=VK_LAYER_OBS_vkcapture_*` as enviroment variables.

Game Capture on OBS for Windows has an option to enable Overlays capture.
Would be possible to add a similar option to obs-vkcapture?

**Comment by nowrep** [comment]
If it was possible there wouldn't need to be that workaround :)
