### ISSUE TITLE
Flatpak OBS + non-Flatpak Steam game

### ISSUE THREAD

**Issue by anat0lius** [nowrep/obs-vkcapture#145]
For the case of having OBS installed as Flatpak and Steam as non-Flatpak (rpm), what I understand from the README is that the following applies:

> If you use Flatpak OBS, you need to install Flatpak OBS plugin.

and 

> For capturing games outside Flatpak runtime, you need native build regardless of if you are using Flatpak OBS or not.

1. I have installed the plugin as Flatpak and I managed to build[^1] the project. 
2. I  have set the following launch parameters in my steam game:

```
/home/ender/apps/obs-vkcapture/build/obs-gamecapture %command%
```

3. I have opened OBS and added `Game Capture` source
4. I started the game
5. Alt-tabed to OBS and started recording

The video recorded is just black.

[^1]: For the `libobs` dependency, I have installed `obs-studio-devel` from my package manager (non-Flatpak).

**Comment by nowrep** [comment]
The build instructions mention `make install` which you haven't done.
