### ISSUE TITLE
vkcapture doesn't work on Age of Empires 2 Definite Edition without workaround

### ISSUE THREAD

**Issue by emaxoda** [nowrep/obs-vkcapture#148]
Like the title say if I try to capture this game it won't capture anything unless I restart OBS with the game running and then i get the capture going, there's nothing useful on the steam logs other than getting the capture to work with the workaround.

[steamlogs.txt](https://github.com/nowrep/obs-vkcapture/files/11256532/steamlogs.txt)

[obs-normal.txt](https://github.com/nowrep/obs-vkcapture/files/11256544/obs-normal.txt)

[obs-restart.txt](https://github.com/nowrep/obs-vkcapture/files/11256541/obs-restart.txt)

**Comment by nowrep** [comment]
Can you try running the game with `env OBS_VKCAPTURE=1 %command%` instead of obs-gamecapture?

**Comment by nowrep** [comment]
Yes, if the game uses both OpenGL and Vulkan it can cause issues.
I'm not exactly sure what's happening in this case, but I think there are two connections from the game and the OpenGL connection wins (the order from your log is: vulkan -> vulkan destroy -> opengl -> vulkan). And if you restart OBS the Vulkan connection wins because the OpenGL connection is no longer presenting?

**Comment by nowrep** [comment]
#149 should workaround/fix this.

**Comment by emaxoda** [comment]
it fixes the problem i was having while using obs-gamecapture

**Comment by nowrep** [comment]
> by the way I know this is not the channel but I saw you have a branch on obs called amf-linux-tex, I've been using your pull request for amf on linux for a long time now, what's the difference between those two?

It uses texture encode aka "zero copy", so instead of downloading the rendered scene from GPU to CPU and then uploading it back to GPU when encoding it keeps the data on GPU.

**Comment by emaxoda** [comment]
i've been using the commits since I asked, so thanks for all the work you do!
