### ISSUE TITLE
unable to find any captureable game 

### ISSUE THREAD

**Issue by KaziiTheAvali** [nowrep/obs-vkcapture#156]
i know i have had this problem befor but the fix is not working on the new distro. from the debug info i am looking at it looks like the layer is unloading itself however i do not know why. obs log is from the obs itself and vseefacelog is what i got running PROTON_LOG=1 OBS_VKCAPTURE=1 VK_LOADER_DEBUG=all obs-gamecapture lutris lutris:rungameid/3 (this does not make a deticated log file)
[obslog.txt](https://github.com/nowrep/obs-vkcapture/files/11728988/obslog.txt)
[VSEEFaceLog.txt](https://github.com/nowrep/obs-vkcapture/files/11728990/VSEEFaceLog.txt)

**Comment by nowrep** [comment]
I see it tries to load both GL and Vulkan capture. So is VSEEFace using Vulkan or OpenGL for presenting (which is what gets captured)?

Try just `OBS_VKCAPTURE=1` without `obs-gamecapture`.

**Comment by nowrep** [comment]
Any updates on this?

**Comment by KaziiTheAvali** [comment]
i thoight you already helped me with this sorry. anways we did find out the problems it was loading litrus and not vseeface. I'm putting it into the launch arguments fixed it
