### ISSUE TITLE
OBS-VKCAPTURE 1.4 fatal error: obs-nix-platform.h: No such file or directory

### ISSUE THREAD

**Issue by Lenny003** [nowrep/obs-vkcapture#158]
Tried compiling the latest version of obs-vkcapture kept getting this error fatal error: obs-nix-platform.h: No such file or directory. Finally got it working when I copied obs-nix-platform.h from /usr/include/obs/obs-nix-platform.h to /usr/local/include/obs-nix-platform.h, however now I get a new error 

[output.txt](https://github.com/nowrep/obs-vkcapture/files/11943635/output.txt)

Using latest obs-studio from arch repos, tried both obs-vkcapture and obs-vkcapture-git from aur, same issues for both

**Comment by nowrep** [comment]
You need to post full build output.

Also it seems like you have old obs installation in `/usr/local` and it's using it instead.

**Comment by Lenny003** [comment]
Alright sorry, heres a full output of a cleanbuild through yay

[output.txt](https://github.com/nowrep/obs-vkcapture/files/11952482/output.txt)

**Comment by Lenny003** [comment]
Alright I figured out the issue, somehow it was searching for rpan-studio in my yay folder, it had failed to build, `libobs.so.0` was not there so it couldnt build it properly. After I removed rpan-studio from my yay folder everything builds fine now.
