### ISSUE TITLE
obs-vkcapture doesnt capture lutris

### ISSUE THREAD

**Issue by KaziiTheAvali** [nowrep/obs-vkcapture#159]
it will not capture anything litrus. you will have to use the native wine application. when running obs-gamecapture lutris lutris:rungameid/id it will just put this[1] as log then cancel itself
[1]
![image](https://github.com/nowrep/obs-vkcapture/assets/87594664/ddd79af8-35b2-4e42-96a5-c5ea1b87dd52)
wine apps will capture tho
info 
![image](https://github.com/nowrep/obs-vkcapture/assets/87594664/56eeb808-0e69-41d8-8ff5-28dff3562b82)
.

**Comment by nowrep** [comment]
You should only enable capture for the games launched by lutris, not for lutris itself.

**Comment by KaziiTheAvali** [comment]
i do not mean to reopen this and sorry if it does however how would i go about doing this.

**Comment by nowrep** [comment]
For each game open properties and add environment variable `OBS_VKCAPTURE=1` or change the launch command to something like `obs-gamecapture %command%` (this is Steam syntax, so lutris may be different).

**Comment by KaziiTheAvali** [comment]
obs_vkcapture (or set obs_vkcapture one in my end) may work however obs-gamecapture wolnt work due to the way to launch a game using litrus is litrus command.

**Comment by KaziiTheAvali** [comment]
i can just use wine tho

**Comment by nowrep** [comment]
You can set `obs-gamecapture` as *Command prefix*

**Comment by KaziiTheAvali** [comment]
neet. thank ya
