### ISSUE TITLE
Doesn't work when mangohud is present.

### ISSUE THREAD

**Issue by kndgs** [nowrep/obs-vkcapture#165]
With mangohud present the desired game/app window doesn's appear in a selectable list nor being captured with "Capture any window" option. 
The issue is present for about a year. Only recently I had time to mess with it and figured it was because of mangohud.

Archlinux 6.5.2-zen1
Nvidia 3060ti 535.104.05
mesa 1:23.1.7
obs 29.1.3
mangohud 0.6.9.1

To recreate use any of: 
mangohud obs-gamecapture glxgears
mangohud --dlsym obs-gamecapture glxgears

**Comment by kndgs** [comment]
Oh I guess it was me failing the proper sequence, works if obs-gamecapture placed before mangohud:
obs-gamecapture mangohud glxgears
obs-gamecapture mangohud --dlsym glxgears

**Comment by nowrep** [comment]
`obs-gamecapture mangohud glxgears` works.

This is mangohud issue, it ignores if the GL functions are already hooked.
