### ISSUE TITLE
env: 'obs-gamecapture': No such file or directory

### ISSUE THREAD

**Issue by deadmeu** [nowrep/obs-vkcapture#168]
**Describe the bug**
Recently, trying to launch a game with obs-gamecapture throws the error `env: 'obs-gamecapture': No such file or directory`
Setting OBS_VKCAPTURE=1 does not work either, as the game capture cannot be found in OBS.

I have everything installed through Flatpaks: Steam, VkCapture, and OBS.

I initially had issues a few days ago with trying to get Terraria to capture properly (different error - something to do with an issue with 32 bit gamecapture not being found), but today I am finding that none of my previously working games are working.

Could this potentially be due to the Steam Flatpak recently updating to Freedesktop runtime 23.08?

**System (please complete the following information):**
- Operating System: Arch Linux 
- KDE Plasma Version: 5.27.8
- KDE Frameworks Version: 5.110.0
- Qt Version: 5.15.10
- Kernel Version: 6.5.4-arch2-1 (64-bit)
- Graphics Platform: Wayland
- Mesa version: mesa 1:23.1.8-1
- com.obsproject.Studio.Plugin.OBSVkCapture/x86_64/stable: 1.4.3
- org.freedesktop.Platform.VulkanLayer.OBSVkCapture/x86_64/22.08: 1.4.3
- com.valvesoftware.Steam/x86_64/stable: 1.0.0.78

**Game log:**
```
/bin/sh\0-c\0gamemoderun obs-gamecapture /home/alex/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=730 -- /home/alex/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/media/EVO/data/Games/SteamLibrary/steamapps/common/Counter-Strike Global Offensive/csgo.sh' -steam -vulkan -nojoy -novid\0
chdir "/media/EVO/data/Games/SteamLibrary/steamapps/common/Counter-Strike Global Offensive"
ERROR: ld.so: object '/home/alex/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/alex/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/alex/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
env: 'obs-gamecapture': No such file or directory
Uploaded AppInterfaceStats to Steam
```

**Comment by nowrep** [comment]
> Could this potentially be due to the Steam Flatpak recently updating to Freedesktop runtime 23.08?

Yes, very likely.

@SuNNjek

**Comment by SuNNjek** [comment]
> Could this potentially be due to the Steam Flatpak recently updating to Freedesktop runtime 23.08?

Yes, the runtime version needs to match. A 23.08 version of the Vulkan layer already exists, so if you just install it, it should work again.

**Comment by SuNNjek** [comment]
> Is there a way this could have been avoided? It would be nice if flatpak update would have told me to update org.freedesktop.Platform.VulkanLayer.OBSVkCapture to 23.08 or maybe just automatically done it for me 🤔

Yeah, that would be really nice but as far as I know there's currently no way to automatically update the flatpak. Technically these are separate versions so it wouldn't really be an update because you can have both versions installed at the same time. Maybe that's why there's no automatic update
