### ISSUE TITLE
[idea] Pipewire video/desktop source

### ISSUE THREAD

**Issue by PedroHLC** [nowrep/obs-vkcapture#17]
First of all, this is not an issue, just a discussion/feedback/decision-log. Feel free to close it at any moment.

VKCapture is, from all the sources I have available in OBS, the one that less impacts gaming performance. And it does not capture my system's screen. It's awesome!

It would be cool to have it pipewire-compatible to share games directly to Firefox/Chromium/Electron/Telegram (I know those supports pipewire for screen sharing).

Or even maybe having OBS output back as a pipewire-source as it does when "virtualising camera".

**Comment by nowrep** [comment]
For that it would be needed to implement screencast xdg-portal (org.freedesktop.portal.ScreenCast). It can be either directly `obs-vkcapture -> portal` or via OBS `obs-vkcapture -> OBS -> portal` which would allow to send any OBS scene into applications supporting the screencast portal.

Sounds like a neat idea, but it really is out of scope here.

**Comment by Sethox** [comment]
With my little knowledge of the portal, I assume it's not possible to add mouse pointer right?

**Comment by nowrep** [comment]
Add mouse pointer where?

**Comment by PedroHLC** [comment]
> With my little knowledge of the portal, I assume it's not possible to add mouse pointer right?

It's possible: https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#gdbus-property-org-freedesktop-portal-ScreenCast.AvailableCursorModes

Note that nowrep solution does not use portals.

**Comment by Zeioth** [comment]
Sorry for bumping, but this would be awesome. I can't use it on wayland/sway without it.

**Comment by nowrep** [comment]
What does this issue have to do with sway/wayland?

This issue is about exporting the OBS scene through pipewire so you can use it as a source eg. in Firefox for webcalls. I'm closing it now to not confuse people, it is out of scope here.
