### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by baaannnaaannn** [nowrep/obs-vkcapture#170]
It says "No Game Capture source available in OBS 27

If you are on X11, make sure you run OBS with EGL enabled: OBS_USE_EGL=1 obs"

On x11 system with OBS 28 and above do I run obs with EGL enabled?

**Comment by nowrep** [comment]
If you are on OBS 28 and newer you don't need to do anything, EGL is enabled by default (and is the only option).

**Comment by baaannnaaannn** [comment]
> If you are on OBS 28 and newer you don't need to do anything, EGL is enabled by default (and is the only option).

Ty,this program/package was awesome
