### ISSUE TITLE
out of date version of vk capture for flatpak beta

### ISSUE THREAD

**Issue by pollux56** [nowrep/obs-vkcapture#176]
**Describe the bug**
i would like to use obs beta with vkcapture but it doesnt seem to work as its either out of date or something else is happening that needs to be fixed upstream 
**Screenshots or video**
If applicable, add screenshots or video to help explain your problem.

![Screenshot_20231026_161929](https://github.com/nowrep/obs-vkcapture/assets/81181814/0aea08d6-f4e0-4f7c-98b5-ebe587d65b93)

**System (please complete the following information):**
 - OS: nobara
 - GPU: 6700 10gb
 - Mesa version: 23.2.1
 - obs-vkcapture version: 1.2.0

**OBS log:**
```
https://obsproject.com/logs/kbPNnmGFQFBjHeAh

Paste OBS log here.
```
OBS 30.0.0-rc1 log file uploaded at 2023-10-26, 16:20:06

16:18:16.085: Platform: Wayland
16:18:16.086: CPU Name: AMD Ryzen 7 3700X 8-Core Processor
16:18:16.086: CPU Speed: 1862.996MHz
16:18:16.086: Physical Cores: 8, Logical Cores: 16
16:18:16.086: Physical Memory: 15877MB Total, 690MB Free
16:18:16.086: Kernel Version: Linux 6.5.8-200.fsync.fc38.x86_64
16:18:16.086: Flatpak Branch: beta
16:18:16.086: Flatpak Arch: x86_64
16:18:16.086: Flatpak Runtime: runtime/org.kde.Platform/x86_64/6.5
16:18:16.086: App Extensions:
16:18:16.086:  - com.obsproject.Studio.Plugin.OBSVkCapture
16:18:16.086:  - org.freedesktop.LinuxAudio.Plugins.TAP
16:18:16.086:  - org.freedesktop.LinuxAudio.Plugins.swh
16:18:16.086:  - com.obsproject.Studio.Locale
16:18:16.086: Runtime Extensions:
16:18:16.086:  - org.freedesktop.Platform.GL.default
16:18:16.086:  - org.freedesktop.Platform.openh264
16:18:16.086:  - org.freedesktop.Platform.VulkanLayer.OBSVkCapture
16:18:16.086:  - org.gtk.Gtk3theme.Breeze
16:18:16.086:  - org.gtk.Gtk3theme.adw-gtk3-dark
16:18:16.086:  - org.kde.Platform.Locale
16:18:16.086:  - org.freedesktop.Platform.GL.default
16:18:16.086: Flatpak Framework Version: 1.15.4
16:18:16.086: Desktop Environment: KDE (KDE)
16:18:16.086: Session Type: wayland
16:18:16.088: Qt Version: 6.5.3 (runtime), 6.5.3 (compiled)
16:18:16.089: Portable mode: false
16:18:16.118: OBS 30.0.0-rc1 (linux)
16:18:16.118: ---------------------------------
16:18:16.118: ---------------------------------
16:18:16.118: audio settings reset:
16:18:16.118: 	samples per sec: 48000
16:18:16.118: 	speakers:        2
16:18:16.118: 	max buffering:   960 milliseconds
16:18:16.118: 	buffering type:  dynamically increasing
16:18:16.121: ---------------------------------
16:18:16.121: Initializing OpenGL...
16:18:16.121: Using EGL/Wayland
16:18:16.149: Initialized EGL 1.5
16:18:16.169: Loading up OpenGL on adapter AMD AMD Radeon Graphics (navi22, LLVM 15.0.7, DRM 3.54, 6.5.8-200.fsync.fc38.x86_64)
16:18:16.169: OpenGL loaded successfully, version 4.6 (Core Profile) Mesa 23.1.9 (git-acb5ee278a), shading language 4.60
16:18:16.203: ---------------------------------
16:18:16.203: video settings reset:
16:18:16.203: 	base resolution:   1920x1080
16:18:16.203: 	output resolution: 1920x1080
16:18:16.203: 	downscale filter:  Bicubic
16:18:16.203: 	fps:               60/1
16:18:16.203: 	format:            NV12
16:18:16.203: 	YUV mode:          Rec. 709/Partial
16:18:16.203: NV12 texture support not available
16:18:16.203: P010 texture support not available
16:18:16.205: Audio monitoring device:
16:18:16.205: 	name: Default
16:18:16.205: 	id: default
16:18:16.205: ---------------------------------
16:18:16.220: No AJA devices found, skipping loading AJA UI plugin
16:18:16.220: Failed to initialize module 'aja-output-ui.so'
16:18:16.233: No AJA devices found, skipping loading AJA plugin
16:18:16.233: Failed to initialize module 'aja.so'
16:18:16.239: Failed to load 'en-US' text for module: 'decklink-captions.so'
16:18:16.245: Failed to load 'en-US' text for module: 'decklink-output-ui.so'
16:18:16.252: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
16:18:16.252: Failed to initialize module 'decklink.so'
16:18:16.433: [pipewire] Available captures:
16:18:16.433: [pipewire]     - Desktop capture
16:18:16.433: [pipewire]     - Window capture
16:18:16.457: [obs-browser]: Version 2.22.1
16:18:16.457: [obs-browser]: CEF Version 103.0.5060.134 (runtime), 103.0.0-5060-shared-textures.2592+g5fc3b43+chromium-103.0.5060.134 (compiled)
16:18:16.476: VAAPI: API version 1.18
16:18:16.478: FFmpeg VAAPI H264 encoding supported
16:18:16.483: FFmpeg VAAPI HEVC encoding supported
16:18:16.568: [obs-websocket] [obs_module_load] you can haz websockets (Version: 5.3.1 | RPC Version: 1)
16:18:16.568: [obs-websocket] [obs_module_load] Qt version (compile-time): 6.5.3 | Qt version (run-time): 6.5.3
16:18:16.568: [obs-websocket] [obs_module_load] Linked ASIO Version: 102800
16:18:16.572: [obs-websocket] [obs_module_load] Module loaded.
16:18:16.606: Failed to load 'en-GB' text for module: 'linux-vkcapture.so'
16:18:16.607: [linux-vkcapture] plugin loaded successfully (version 1.2.0)
16:18:16.607: ---------------------------------
16:18:16.607:   Loaded Modules:
16:18:16.607:     linux-vkcapture.so
16:18:16.607:     text-freetype2.so
16:18:16.607:     rtmp-services.so
16:18:16.607:     obs-x264.so
16:18:16.607:     obs-websocket.so
16:18:16.607:     obs-webrtc.so
16:18:16.607:     obs-vst.so
16:18:16.607:     obs-transitions.so
16:18:16.607:     obs-qsv11.so
16:18:16.607:     obs-outputs.so
16:18:16.607:     obs-libfdk.so
16:18:16.607:     obs-filters.so
16:18:16.607:     obs-ffmpeg.so
16:18:16.607:     obs-browser.so
16:18:16.607:     linux-v4l2.so
16:18:16.607:     linux-pulseaudio.so
16:18:16.607:     linux-pipewire.so
16:18:16.607:     linux-jack.so
16:18:16.607:     linux-capture.so
16:18:16.607:     image-source.so
16:18:16.607:     frontend-tools.so
16:18:16.607:     decklink-output-ui.so
16:18:16.607:     decklink-captions.so
16:18:16.607: ---------------------------------
16:18:16.607: QWidget::setTabOrder: 'first' and 'second' must be in the same window
16:18:16.607: ==== Startup complete ===============================================
16:18:16.653: All scene data cleared
16:18:16.653: ------------------------------------------------
16:18:16.657: pulse-input: Server name: 'PulseAudio (on PipeWire 0.3.82) 15.0.0'
16:18:16.657: pulse-input: Audio format: s32le, 48000 Hz, 2 channels
16:18:16.657: pulse-input: Started recording from 'alsa_output.pci-0000_09_00.4.analog-stereo.monitor' (default)
16:18:16.657: [Loaded global audio device]: 'Desktop Audio'
16:18:16.658: pulse-input: Server name: 'PulseAudio (on PipeWire 0.3.82) 15.0.0'
16:18:16.658: pulse-input: Audio format: s16le, 48000 Hz, 1 channels
16:18:16.658: pulse-input: Started recording from 'alsa_input.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-mono'
16:18:16.658: [Loaded global audio device]: 'Mic/Aux'
16:18:16.658:     - filter: 'Limiter' (limiter_filter)
16:18:16.658:     - filter: 'Noise Suppression' (noise_suppress_filter_v2)
16:18:16.658:     - filter: 'Noise Gate' (noise_gate_filter)
16:18:16.660: Switched to scene 'Scene'
16:18:16.660: ------------------------------------------------
16:18:16.660: Loaded scenes:
16:18:16.660: - scene 'Scene':
16:18:16.660: ------------------------------------------------
16:18:17.228: adding 21 milliseconds of audio buffering, total audio buffering is now 21 milliseconds (source: Desktop Audio)
16:18:17.228: 
16:18:17.249: adding 21 milliseconds of audio buffering, total audio buffering is now 42 milliseconds (source: Mic/Aux)
16:18:17.249: 
16:18:21.917: ext_screencopy_manager_v1 not available
16:18:21.921: User added source 'Game Capture' (vkcapture-source) to scene 'Scene'

**Game log:**
```
Paste game terminal output here.
```

**Comment by nowrep** [comment]
You didn't post game log so I can't tell what version the game runs. I assume if you use obs-vkcapture 1.2.0 on host it should work, or do you use Steam flatpak too?

But the beta flatpak version seems to be too old (1.2.0) - @SuNNjek

**Comment by pollux56** [comment]
> You didn't post game log so I can't tell what version the game runs. I assume if you use obs-vkcapture 1.2.0 on host it should work, or do you use Steam flatpak too?
> 
> But the beta flatpak version seems to be too old (1.2.0) - @SuNNjek 

Oh ok i completely forgot i would need 1.2 system version aswell, i will close this sorry

**Comment by SuNNjek** [comment]
> You didn't post game log so I can't tell what version the game runs. I assume if you use obs-vkcapture 1.2.0 on host it should work, or do you use Steam flatpak too?
> 
> But the beta flatpak version seems to be too old (1.2.0) - @SuNNjek

I don't have automatic updates set up for the beta branch, so yeah, this is still at version 1.2.0. I could set that up though, I think this is the second time there was an issue where people tried using it with the OBS beta 😅

**Comment by pollux56** [comment]
> > You didn't post game log so I can't tell what version the game runs. I assume if you use obs-vkcapture 1.2.0 on host it should work, or do you use Steam flatpak too?
> > But the beta flatpak version seems to be too old (1.2.0) - @SuNNjek
> 
> I don't have automatic updates set up for the beta branch, so yeah, this is still at version 1.2.0. I could set that up though, I think this is the second time there was an issue where people tried using it with the OBS beta 😅

i would love that ngl, their is a decent amount of obs updates that are happening for linux and they seem to be taking a while to release obs beta 30 so i would love it if you were able to set this up but thats completely up to you

**Comment by SuNNjek** [comment]
@pollux56 I have updated the beta branch now. Flathub usually takes a while (3-4 hours I think) before builds are available for download. So after that time you can try and update the beta plugin again :smile:

**Comment by pollux56** [comment]
> @pollux56 I have updated the beta branch now. Flathub usually takes a while (3-4 hours I think) before builds are available for download. So after that time you can try and update the beta plugin again :smile: 

Thank you so much, i rlly do appreciate it :)

**Comment by pollux56** [comment]
> > @pollux56 I have updated the beta branch now. Flathub usually takes a while (3-4 hours I think) before builds are available for download. So after that time you can try and update the beta plugin again 😄
> 
> Thank you so much, i rlly do appreciate it :)

got the update and it now works, thank you :D
