### ISSUE TITLE
OBS Game Capture option is not appearing.

### ISSUE THREAD

**Issue by ElectricLizzzard** [nowrep/obs-vkcapture#177]
After binary is built with all (even optional) dependencies and installed, OBS just don't detect Game Capture option whatsoever. All compiled binaries are in their place in /usr directory as well.

Bug is easy to replicate.

 - OS: Debian 12 Bookworm
 - GPU: Radeon R9 380
 - Mesa version: 22.3.6
 - obs-vkcapture version: 1.4.4
 
 Unfortunately there is no logs or output to post.

**Comment by nowrep** [comment]
There is a "Bug report" issue template that you should use.

> Unfortunately there is no logs or output to post.

There are always logs to post. Post full OBS log and also where did you install the plugin.

**Comment by ElectricLizzzard** [comment]
[install_log.txt](https://github.com/nowrep/obs-vkcapture/files/13198384/install_log.txt)
[obs_log.txt](https://github.com/nowrep/obs-vkcapture/files/13198385/obs_log.txt)

I decided to redo my steps and show you. Looks like OBS just not loading these plugins.

**Comment by nowrep** [comment]
You need to install libwayland-dev.

**Comment by ElectricLizzzard** [comment]
Thank you! Problem solved
