### ISSUE TITLE
Blank screen with flatpak OBS and non-flatpak steam

### ISSUE THREAD

**Issue by ToRRent1812** [nowrep/obs-vkcapture#182]
Hi, I would like to capture non-flatpak steam(rpm) with flatpak obs. Based of this [instruction](https://github.com/nowrep/obs-vkcapture/issues/145#issuecomment-1502245575), I built native version. 
So I downloaded vkcapture flatpak plugin, and built native version.
Unfortunately when using game capture layer, it still won't detect game window. If I delete flatpak plugin, game capture option is gone.

Is there anything extra I need to do to bring native game windows to capture in flatpak obs?

**Comment by nowrep** [comment]
> Is there anything extra I need to do

Post logs

**Comment by ToRRent1812** [comment]
Sorry, here we go.

[steam-218620.log](https://github.com/nowrep/obs-vkcapture/files/13340315/steam-218620.log)
[2023-11-13 20-39-30.txt](https://github.com/nowrep/obs-vkcapture/files/13340318/2023-11-13.20-39-30.txt)

**Comment by nowrep** [comment]
Does it work with vkcube? `OBS_VKCAPTURE=1 vkcube`

**Comment by ToRRent1812** [comment]
Interesting, looks like it does work. Maybe the issue is payday related, I will download few more games to test.

**Comment by nowrep** [comment]
I'm not sure what's going on actually, in the log it shows that the layer doesn't see any CreateSwapchainKHR call but it also clearly shows that DXVK does create one. If you can check with some other games using Proton and see if the same thing happens.

**Comment by ToRRent1812** [comment]
Hi, I've tested few more games and it looks like I can only capture 64 bit games.

**Comment by nowrep** [comment]
For 32bit games you also need to build the layer (capture tools) as 32bit, did you do that?

**Comment by ToRRent1812** [comment]
I think so yes, linux-vkcapture.so is on lib/obs-plugins folder

**Comment by nowrep** [comment]
That's the OBS plugin, which you only need 64bit.

Vulkan layer: `/usr/lib32/libVkLayer_obs_vkcapture.so` + `/usr/share/vulkan/implicit_layer.d/obs_vjkkcapture_32.json`
OpenGL lib: `/usr/lib32/libobs_glcapture.so`

These are paths on ArchLinux so may be different on Fedora.

Also please build from git, I've added a log message that will show if 32 or 64bit obs-vkcapture library is loaded.

**Comment by ToRRent1812** [comment]
Ah, that makes sense.
I don't have libVkLayer_obs_vkcapture.so in /usr/lib but it's in /usr/lib64. Unfortunately I don't know how to build 32bit version so I will just leave it as it is, thanks for help.

**Comment by nowrep** [comment]
https://github.com/nowrep/obs-vkcapture/blob/0fb5dc46e2f04fc1511ff9bd1e7f6b0e09100e2f/dist/PKGBUILD#L26
