### ISSUE TITLE
Black screen when recording, shows mouse and resolution but nothing else

### ISSUE THREAD

**Issue by Sorrydough** [nowrep/obs-vkcapture#187]
Black screen when recording, shows mouse and resolution but nothing else

![behavior screenshot](https://github.com/nowrep/obs-vkcapture/assets/91179164/af953d70-af97-48c8-9e38-d663d3871f34)

 - OS: Arch Btw
 - GPU: Radeon 5700XT
 - Mesa version:  Mesa 23.2.1-arch1.2
 - obs-vkcapture version: OBS Studio - 29.1.3-1
 - Driver Package: amdvlk (not vulkan-radeon)

[OBS log](https://github.com/nowrep/obs-vkcapture/files/13509529/2023-11-30.00-56-19.txt)

[vkcube log](https://github.com/nowrep/obs-vkcapture/files/13509538/vkcube.log.txt)

Everything worked fine for me in the past. It's been like 4 months since then. It randomly stopped working one day. I couldn't find anything in any logs to troubleshoot it myself, so I just forgot about it thinking that a package updated or whatever hoping it would automatically fix itself at some point. But that hasn't happened so here you go. I'm using amdvlk and not vulkan-radeon because I was having bugs with the latter. I was in X11 for these logs, but I usually use wayland and it doesn't work there either.

**Comment by nowrep** [comment]
It seems to be broken with amdvlk, I can reproduce myself.

**Comment by nowrep** [comment]
This works `OBS_VKCAPTURE_LINEAR=1 OBS_VKCAPTURE=1 vkcube`
