### ISSUE TITLE
protobuf: Padding in C structs can be strange.

### ISSUE THREAD

**Issue by cheako** [nowrep/obs-vkcapture#19]
Generalize the IPC to allow development of vkcapture aware applications.

Edit: The issue is compatibility with other programming languages, it's unsafe to try and match a C struct...  where the choice of llvm or gcc could become important.  Specifically, I'm writing in Rust and as explicitly adding 4 bytes of padding would work it's not as ideal as switching to something else...  The use of bool is also suspicious.

I've arbitrarily chosen: https://github.com/eerimoq/pbtools

**Comment by cheako** [comment]
@nowrep The use case described by the PR is in an issue.  Is it not better to use something more resembling a protocol instead of just baling if the size isn't what you'd expect.

**Comment by nowrep** [comment]
I don't see how it is unsafe. The struct gets compiled to exactly the same layout on any compiler, it's not "strange" and also I don't see how it can be unsafe.

>  The use of bool is also suspicious.

What's wrong with bool? There is a padding added after the bool variable (for 4-byte alignment).

I don't really see any justification at all to add that amount of extra code. It doesn't solve anything really.

>  Is it not better to use something more resembling a protocol instead of just baling if the size isn't what you'd expect

You still bail if you can't decode the protobuf data, so this "problem" is still there.

**Comment by cheako** [comment]
I did break out a sledgehammer.  Other less intrusive options might be to implicitly insert the padding and use canonical types, `s/ int / int32_t / s/bool/int8_t/`.  I rejected that idea because it seemed like a half-measure, potentially a problem later.  Speaking of later, see the current requirement to keep client and server version locked.  Directly using a struct like this seems like it would cause interoperability issues.  I choose pbtools basically at random, so am open to other solutions.

I'm not really an expert in C, but it seems you're relying on undefined behavior.  The C spec doesn't say anything about the size of bool, so a compiler could choose the first, second, fourth or eighth LE address to use as containing the significant bit.  I can't explain the padding, only that it's a big red flag according to Rust.

As far as observed results using any compiler, that obviously doesn't extend to compilers that haven't been written and as I've explained other languages have trouble matching C's behavior.  Keep in mind that ARM laptops are becoming a thing and specifying compiler intricacies into Rust isn't going to be conditional on arch...  Until fixing bugs related to running on ARM, and then repeat this process assuming RISC-V becomes a thing years later.

**Comment by nowrep** [comment]
I'm open to something like this https://gist.github.com/nowrep/b1ccfa54caaf6c79e6a909ea879d590a - it fixes the theoretical issue with type sizes and also adds padding to the end of structure allowing to extend it without breaking backwards compatibility.

>  The C spec doesn't say anything about the size of bool, so a compiler could choose the first, second, fourth or eighth LE address to use as containing the significant bit. I can't explain the padding, only that it's a big red flag according to Rust.

Since it's a bool it doesn't really matter as `if (bool_var)` == `if ((int)bool_var != 0)`.

> As far as observed results using any compiler, that obviously doesn't extend to compilers that haven't been written and as I've explained other languages have trouble matching C's behavior. 

This code will only realistically run on x86/_64 + gcc/clang and there you have int = 4 bytes. I'm sorry, but I'm not adding thousands of lines of code for basically nothing in return. I prefer to keep things simple, if at all possible.

And you really shouldn't have any issues reproducing the same struct in Rust, Python, even in JavaScript.
