### ISSUE TITLE
unable to capture HDR.

### ISSUE THREAD

**Issue by GloriousEggroll** [nowrep/obs-vkcapture#199]
Not sure if this is on the OBS side or the game capture side. I was messing around with capturing helldivers using gamecapture (monitor is 32:9 so no capture card will work at that resolution ratio), made a recording and the colors are all washed out due to the source being captured as SDR.

How am I setting this up for HDR?:

KDE 6 to enable hdr on displays + gamescope (need built from git):
`gamescope --hdr-enabled -w 5120 -W 5120 -h 1440 -H 1440 -b -- mangohud %command%`

OBS advanced video settings are also setup for P010 2100 PQ

I've also verified HDR recording works as intended in OBS when using my El Gato 4K X.

**Comment by nowrep** [comment]
It's not implemented yet. Missing swapchain HDR metadata and plugin needs to be updated to correctly render it. And on the vaapi encoder side this needs HDR metadata support for HEVC in mesa and for AV1 it needs to be implemented first in ffmpeg.

**Comment by nowrep** [comment]
Try with `master`, you'll need to set `OBS_VKCAPTURE_COLOR_SPACE=2` for games running inside gamescope because the WSI layer resets color space to RGB (or make the vkcapture layer ordered before wsi layer).
