### ISSUE TITLE
Does this plugin require running a wayland session?

### ISSUE THREAD

**Issue by danyeet** [nowrep/obs-vkcapture#2]
While looking at the repo I didn't see a requirement, running obs gives me this 
`error: [linux-vkcapture] linux-vkcapture cannot run on non-EGL platforms
warning: Failed to initialize module 'linux-vkcapture.so'`
And I am running obs-studio-git.
If wayland is required, it might be a good idea to add it to readme.
Thanks in advance.

**Comment by nowrep** [comment]
Start obs with `OBS_USE_EGL=1 obs`

**Comment by danyeet** [comment]
Thanks a lot.

**Comment by nowrep** [comment]
I'll add it to README, I forgot about this.

**Comment by danyeet** [comment]
BTW, running obs with this env variable seems to break Display capture and window capture so that's fun. 
Does it work on your side with whatever you use?

**Comment by nowrep** [comment]
Screen/Window capture needs glx, so it won't work with egl.

And no, I have no idea how to fix those errors, sorry.

**Comment by danyeet** [comment]
No worries - just one more question 
Do you run NVIDIA or something else ?|
And thanks for at least making this even though I cant seem to make it work : D.

**Comment by nowrep** [comment]
No, I have AMD.

**Comment by danyeet** [comment]
Thanks.Well hopefully something happens so these get fixed - or at least I'll get something with linux in mind next time. Thanks for trying to tackle this issue - it would be great if it gets merged or at least getting OBS on linux to equal grounds with the other platforms.
