### ISSUE TITLE
OBS Vulkan Capture stopped working for games running via Proton

### ISSUE THREAD

**Issue by VortexAcherontic** [nowrep/obs-vkcapture#204]
**Describe the bug**
Hello there,

since some time now VKCapture stopped working for games I run via Steam + Proton.
Native Linux games running via Steam both do work just fine.
But also MangoHUD disappeared for Proton titles so it might be a Runtime issue by Steam itself not sure at this point.

It is like VKCapture never noticed any Vulkan application was launched.

Furthermore I'd like to mention I run all software via Flatpak:

- Steam with Runtime: org.freedesktop.Platform/x86_64/23.08
- OBS Studio with Runtime: org.kde.Platform/x86_64/6.5
- com.obsproject.Studio.Plugin.OBSVkCapture
- org.freedesktop.Platform.VulkanLayer.OBSVkCapture Branch: 23.08

Adding to the confusion the Plugin itself report 1.5.0 in the logs as it's version while flatpak says its version 1.4.9

**System (please complete the following information):**
 - OS: openSUSE Aeon
 - GPU: nVidia RTX 3080
 - Driver version: 550.67
 - obs-vkcapture version: 1.4.9 or 1.5.0 intel on the version is not clear. Logs say 1.5.0, flatpak info says 1.4.9

**OBS log:**
https://gist.github.com/VortexAcherontic/61b659cb57aba03558be295149454011

**Game log:**
Not working scenario: https://gist.github.com/VortexAcherontic/8e6207ee84bfcd7930b8896b3e82411d

Working scenario: 
https://gist.github.com/VortexAcherontic/e6a13f4aeb2a2056ba0a67ee897c7dba

**Comment by nowrep** [comment]
Duplicate of #200 ?

**Comment by Pimsta** [comment]
i had same issue but flatpak steam just had an update and it fixed it

**Comment by VortexAcherontic** [comment]
> i had same issue but flatpak steam just had an update and it fixed it

You are right, jsut got the update and it works now.

Sorry @nowrep for bothering you guys it was flatpak Steam. Now everything works as expected. ❤️
