### ISSUE TITLE
Plans to make obs-vkcapture more quiet?

### ISSUE THREAD

**Issue by strycore** [nowrep/obs-vkcapture#207]
On default Nobara installs, obs-vkcapture is enabled by default. 

This can result in a lot of logs that don't create any value such as this:

![image](https://github.com/nowrep/obs-vkcapture/assets/280336/797caa1c-2cc1-4780-93d3-e9d333f13821)

My question is : will you consider removing the "Init Vulkan" message?

**Comment by nowrep** [comment]
You can set `OBS_VKCAPTURE_QUIET=1` to disable all messages.
