### ISSUE TITLE
Does an environment variable exist for obs-gamecapture?

### ISSUE THREAD

**Issue by ExecratedEdits** [nowrep/obs-vkcapture#208]
Similar to OBS_VKCAPTURE=1 for substituting `obs-vkcapture %command%`, I was looking for a way to apply `obs-gamecapture %command%` for all Steam games (flatpak version) without manual entry but couldn't find an equivalent in the documentation.

**Comment by nowrep** [comment]
You can check what the `obs-gamecapture` script does. For OpenGL it uses `LD_PRELOAD`, but I don't recommend setting it system-wide as it would be loaded into all processes (not just those using OpenGL).

**Comment by ExecratedEdits** [comment]
Understood, thanks for clarifying.
