### ISSUE TITLE
Feature request: Possible environment variable to capture?

### ISSUE THREAD

**Issue by obsgamecapture** [nowrep/obs-vkcapture#210]
So now i can set OBS_VKCAPTURE=1 in Flatseal to any program i want to have Vulkan game capture by default.
It captures only Vulkan though and not OpenGL. Could there be improvement to have a environment variable that would set both Vulkan and OpenGL capture to be used?

The command obs-gamecapture is only recognized in Steam and i cannot set it as a command to launch an application in terminal for example.

I have everything installed as Flatpak.

**Comment by nowrep** [comment]
You can see https://github.com/nowrep/obs-vkcapture/blob/master/src/obs-gamecapture.in how it works, for OpenGL it uses `LD_PRELOAD` so while you could set it system-wide it would be loaded into **every** process you run.
