### ISSUE TITLE
game capture will capture game video, but not audio

### ISSUE THREAD

**Issue by sirus20x6** [nowrep/obs-vkcapture#211]
**Describe the bug**
installed obs-vkapture, launched game with obs-gamecapture %command%, added game capture to source and selected my game, audio mixer only shows "desktop audio" and I can't select anything else and all my audio comes through it.

**Screenshots or video**
If applicable, add screenshots or video to help explain your problem.

**System (please complete the following information):**
 - OS: Linux neuromancer 6.8.9-arch1-2 #1 SMP PREEMPT_DYNAMIC Tue, 07 May 2024 21:35:54 +0000 x86_64 GNU/Linux

 - GPU: 7900xtx
 - Mesa version:
 - vulkaninfo --summary
ERROR: [Loader Message] Code 0 : loader_scanned_icd_add: Could not get 'vkCreateInstance' via 'vk_icdGetInstanceProcAddr' for ICD libGLX_nvidia.so.0
==========
VULKANINFO
==========

Vulkan Instance Version: 1.3.279

Instance Extensions: count = 23
-------------------------------
VK_EXT_acquire_drm_display             : extension revision 1
VK_EXT_acquire_xlib_display            : extension revision 1
VK_EXT_debug_report                    : extension revision 10
VK_EXT_debug_utils                     : extension revision 2
VK_EXT_direct_mode_display             : extension revision 1
VK_EXT_display_surface_counter         : extension revision 1
VK_EXT_surface_maintenance1            : extension revision 1
VK_EXT_swapchain_colorspace            : extension revision 4
VK_KHR_device_group_creation           : extension revision 1
VK_KHR_display                         : extension revision 23
VK_KHR_external_fence_capabilities     : extension revision 1
VK_KHR_external_memory_capabilities    : extension revision 1
VK_KHR_external_semaphore_capabilities : extension revision 1
VK_KHR_get_display_properties2         : extension revision 1
VK_KHR_get_physical_device_properties2 : extension revision 2
VK_KHR_get_surface_capabilities2       : extension revision 1
VK_KHR_portability_enumeration         : extension revision 1
VK_KHR_surface                         : extension revision 25
VK_KHR_surface_protected_capabilities  : extension revision 1
VK_KHR_wayland_surface                 : extension revision 6
VK_KHR_xcb_surface                     : extension revision 6
VK_KHR_xlib_surface                    : extension revision 6
VK_LUNARG_direct_driver_loading        : extension revision 1

Instance Layers: count = 10
---------------------------
VK_LAYER_KHRONOS_validation       Khronos Validation Layer     1.3.275  version 1
VK_LAYER_LUNARG_api_dump          LunarG API dump layer        1.3.250  version 2
VK_LAYER_LUNARG_monitor           Execution Monitoring Layer   1.3.250  version 1
VK_LAYER_LUNARG_screenshot        LunarG image capture layer   1.3.250  version 1
VK_LAYER_NV_optimus               NVIDIA Optimus layer         1.3.277  version 1
VK_LAYER_OBS_vkcapture_64         OBS Linux game capture       1.3.285  version 1
VK_LAYER_VALVE_steam_fossilize_32 Steam Pipeline Caching Layer 1.3.207  version 1
VK_LAYER_VALVE_steam_fossilize_64 Steam Pipeline Caching Layer 1.3.207  version 1
VK_LAYER_VALVE_steam_overlay_32   Steam Overlay Layer          1.3.207  version 1
VK_LAYER_VALVE_steam_overlay_64   Steam Overlay Layer          1.3.207  version 1

Devices:
========
GPU0:
	apiVersion         = 1.3.274
	driverVersion      = 24.0.7
	vendorID           = 0x1002
	deviceID           = 0x744c
	deviceType         = PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
	deviceName         = AMD Radeon RX 7900 XTX (RADV NAVI31)
	driverID           = DRIVER_ID_MESA_RADV
	driverName         = radv
	driverInfo         = Mesa 24.0.7-arch1.3
	conformanceVersion = 1.3.0.0
	deviceUUID         = 00000000-4300-0000-0000-000000000000
	driverUUID         = 414d442d-4d45-5341-2d44-525600000000

 - obs-vkcapture version:

**OBS log:**
> obs
debug: Found portal inhibitor
debug: Attempted path: share/obs/obs-studio/locale/en-US.ini
debug: Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
debug: Attempted path: share/obs/obs-studio/locale.ini
debug: Attempted path: /usr/share/obs/obs-studio/locale.ini
debug: Attempted path: share/obs/obs-studio/themes
debug: Attempted path: /usr/share/obs/obs-studio/themes
debug: Attempted path: share/obs/obs-studio/themes/Yami.qss
debug: Attempted path: /usr/share/obs/obs-studio/themes/Yami.qss
info: Using EGL/X11
info: CPU Name: AMD EPYC 7473X 24-Core Processor
info: CPU Speed: 2800.000MHz
info: Physical Cores: 24, Logical Cores: 48
info: Physical Memory: 515839MB Total, 419342MB Free
info: Kernel Version: Linux 6.8.9-arch1-2
info: Distribution: "Arch Linux" Unknown
info: Desktop Environment: XFCE (XFCE)
info: Session Type: x11
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.21.1
info: Qt Version: 6.7.0 (runtime), 6.7.0 (compiled)
info: Portable mode: false
info: OBS 30.1.2-1 (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 48000
	speakers:        2
	max buffering:   960 milliseconds
	buffering type:  dynamically increasing
info: ---------------------------------
info: Initializing OpenGL...
info: Loading up OpenGL on adapter AMD AMD Radeon RX 7900 XTX (radeonsi, navi31, LLVM 17.0.6, DRM 3.57, 6.8.9-arch1-2)
info: OpenGL loaded successfully, version 4.6 (Core Profile) Mesa 24.0.7-arch1.3, shading language 4.60
info: ---------------------------------
info: video settings reset:
	base resolution:   3840x2160
	output resolution: 1920x1080
	downscale filter:  Bicubic
	fps:               30/1
	format:            NV12
	YUV mode:          Rec. 709/Partial
info: NV12 texture support enabled
info: P010 texture support not available
info: Audio monitoring device:
	name: Default
	id: default
info: ---------------------------------
warning: Failed to load 'en-US' text for module: 'decklink-captions.so'
warning: Failed to load 'en-US' text for module: 'decklink-output-ui.so'
libDeckLinkAPI.so: cannot open shared object file: No such file or directory
warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
warning: Failed to initialize module 'decklink.so'
info: [pipewire] No captures available
warning: v4l2loopback not installed, virtual camera disabled
info: [linux-vkcapture] plugin loaded successfully (version 1.5.0)
info: VAAPI: API version 1.21
info: FFmpeg VAAPI H264 encoding supported
info: FFmpeg VAAPI AV1 encoding supported
info: FFmpeg VAAPI HEVC encoding supported
info: ---------------------------------
info:   Loaded Modules:
info:     text-freetype2.so
info:     rtmp-services.so
info:     obs-x264.so
info:     obs-webrtc.so
info:     obs-vst.so
info:     obs-transitions.so
info:     obs-qsv11.so
info:     obs-outputs.so
info:     obs-libfdk.so
info:     obs-filters.so
info:     obs-ffmpeg.so
info:     linux-vkcapture.so
info:     linux-v4l2.so
info:     linux-pulseaudio.so
info:     linux-pipewire.so
info:     linux-jack.so
info:     linux-capture.so
info:     linux-alsa.so
info:     image-source.so
info:     frontend-tools.so
info:     decklink-output-ui.so
info:     decklink-captions.so
info: ---------------------------------
info: ==== Startup complete ===============================================
info: All scene data cleared
info: ------------------------------------------------
info: pulse-input: Server name: 'PulseAudio (on PipeWire 1.0.6) 15.0.0'
info: pulse-input: Audio format: s32le, 48000 Hz, 2 channels
info: pulse-input: Started recording from 'alsa_output.usb-Schiit_Audio_Schiit_Unison_Modius_E-00.analog-stereo.monitor' (default)
info: pulse-am: Prevented feedback-loop in 'default'
info: [Loaded global audio device]: 'Desktop Audio'
info:     - monitoring: monitor and output
info: pulse-input: Server name: 'PulseAudio (on PipeWire 1.0.6) 15.0.0'
info: pulse-input: Audio format: s32le, 48000 Hz, 8 channels
info: pulse-input: Started recording from 'alsa_input.usb-Focusrite_Vocaster_One_USB_V1QUUVA25005D0-00.pro-input-0'
info: pulse-am: Server name: 'PulseAudio (on PipeWire 1.0.6) 15.0.0'
info: pulse-am: Audio format: s32le, 48000 Hz, 2 channels
info: pulse-am: Started Monitoring in 'alsa_output.usb-Schiit_Audio_Schiit_Unison_Modius_E-00.analog-stereo'
info: pulse-input: Server name: 'PulseAudio (on PipeWire 1.0.6) 15.0.0'
error: pulse-input: An error occurred while getting the source info!
info: pulse-am: Server name: 'PulseAudio (on PipeWire 1.0.6) 15.0.0'
info: pulse-am: Audio format: s32le, 48000 Hz, 2 channels
info: pulse-am: Started Monitoring in 'alsa_output.usb-Schiit_Audio_Schiit_Unison_Modius_E-00.analog-stereo'
info: v4l2-input: Start capture from /dev/video0
error: v4l2-input: Unable to open device
error: v4l2-input: Initialization failed, errno: No such file or directory
info: Switched to scene 'desktop'
info: ------------------------------------------------
info: Loaded scenes:
info: - scene 'Scene':
info:     - source: 'Audio Input Capture (PulseAudio)' (pulse_input_capture)
info:         - monitoring: monitor and output
info:     - source: 'Audio Input Capture (PulseAudio) 2' (pulse_input_capture)
info:         - monitoring: monitor and output
info:     - source: 'Video Capture Device (V4L2)' (v4l2_input)
info: - scene 'desktop':
info:     - source: 'Game Capture' (vkcapture-source)
info: ------------------------------------------------
info: adding 21 milliseconds of audio buffering, total audio buffering is now 21 milliseconds (source: Desktop Audio)

info: adding 21 milliseconds of audio buffering, total audio buffering is now 42 milliseconds (source: Audio Input Capture (PulseAudio))

info: [linux-vkcapture] Client 1 connected (pid=976430)
info: [linux-vkcapture] Creating texture from dmabuf 3840x2160 modifier:72057594037927935
info: [linux-vkcapture]  [0] fd:47 stride:15360 offset:0
info: User Removed source 'Game Capture' (vkcapture-source) from scene 'desktop'
info: [linux-vkcapture] destroy
info: User added source 'Game Capture' (vkcapture-source) to scene 'desktop'
info: [linux-vkcapture] Creating texture from dmabuf 3840x2160 modifier:72057594037927935
info: [linux-vkcapture]  [0] fd:47 stride:15360 offset:0

**Game log:**
```
Paste game terminal output here.
Make sure to set OBS_VKCAPTURE_QUIET=0 environment variable.
```

**Comment by nowrep** [comment]
This plugin only captures video.
