### ISSUE TITLE
Build Fails on Ubuntu for OBS 30.2.0

### ISSUE THREAD

**Issue by FireStarW** [nowrep/obs-vkcapture#218]
Trying to build with the new version of OBS on Ubuntu using the PPA package version (https://launchpad.net/~obsproject/+archive/ubuntu/obs-studio), make fails complaining obs-module.h does not exist, despite cmake finding libobs. 

[cmake_output](https://github.com/user-attachments/files/16238402/cmake_output.txt)
[make_output](https://github.com/user-attachments/files/16238405/make_output.txt)

**System (please complete the following information):**
 - OS: Ubuntu 24.04
 - GPU: Nvidia RTX 2060
 - Mesa version: 
 - obs-vkcapture version:latest git

**Comment by ItsRogueRen** [comment]
Confirming this as not working for the flatpak of OBS 30.2.0 as well

**Comment by Gamertech** [comment]
OBS 30.2 removed a few helpers from libobs and broke every flatpak plugin for it. They all need to be rebuilt for latest libobs :(

Can downgrade OBS to previous version and everything works again with:
`sudo flatpak update --commit=71d974e21fd96594d6ce66314962435a46674e1c441abcc9a6d64cbe5a5f7eda com.obsproject.Studio`

(flatpak needs sudo to downgrade like this).

**Comment by nowrep** [comment]
Can you please provide full build log with the error? It still builds fine for me with OBS git.

**Comment by Gamertech** [comment]
Can't comment on native builds, but here's the freshly wontfix'd OBS issue about 30.2 breaking every flatpak extension.

According to one maintainer, Flathub planned to auto-rebuild the extensions they host a few hours after the OBS release, but there's been zero activity on any of their repos, and a number of plugin authors have commented they need to update to match the new libobs and build against current Flathub.

Without this, flatpak OBS Studio 30.2 wont even try and load any plugins. OBS itself loads and runs fine, but zero functioning extensions whether flatpak or manually installed into the directory.

https://github.com/obsproject/obs-studio/issues/10981

**Comment by nowrep** [comment]
The make output needs to be at least with `make VERBOSE=1` please because the on you posted doesn't show any error.

**Comment by FireStarW** [comment]
[make_output_verbose.txt](https://github.com/user-attachments/files/16256712/make_output_verbose.txt)

**Comment by nowrep** [comment]
Thanks.

It's missing include path, not sure why. Can you try again with latest master, maybe you are hitting the same issue.

**Comment by FireStarW** [comment]
Ok, so I compiled and installed the latest master of obs , specifically into a *.deb file via - https://github.com/obsproject/obs-studio/wiki/Build-Instructions-For-Linux#5-create-a-debian-package

However, I think something was just wrong with my original git clone of the repo, despite a `git pull origin master` giving me the message `Already up to date.` , in that original git clone.

I re-cloned the repo into a new folder and that one compiled obs-vkcapture just fine, for both the manually compiled obs and the PPA package.

There might be some messiness on my system from previously using a manually compiled obs, it was the only way to get a browser source before the OBS PPA package for 24.04 was created last week for the new OBS version, and upon uninstalling that manually compiled *.deb version via apt it would give warnings.
[dpkg-warning.txt](https://github.com/user-attachments/files/16275323/dpkg-warning.txt)


I'm guessing it was just the git repo on my machine though.

either way this issue was unrelated to the flatpak woes...

**Comment by nowrep** [comment]
Ok, so it builds now. Thanks

**Comment by ItsRogueRen** [comment]
Slightly off topic but can you explain everything you did to make a build environment on Ubuntu for this? I've spent hours trying to and I'm having conflicts and dependency hell and I have no idea what I'm doing

**Comment by FireStarW** [comment]
Afraid there's not much to explain, assuming you're talking about compiling OBS, I just followed the instructions from their github wiki I linked before, and did the enable pipewire option. Only curveball I had was missing their download link to the CEF binary.
