### ISSUE TITLE
Vulkan capture not working since 0.7 - RX 5600XT

### ISSUE THREAD

**Issue by Lepidos** [nowrep/obs-vkcapture#22]
Obs stdout:
````
info: [linux-vkcapture] Creating texture from dmabuf 1276x1391 modifier:144115188085734146
info: [linux-vkcapture]  [0] fd:39 stride:5120 offset:0
info: [linux-vkcapture]  [1] fd:40 stride:1536 offset:7208960
error: Cannot create EGLImage: Arguments are inconsistent (for example, a valid context requires buffers not supplied by a valid surface).
error: [linux-vkcapture] Could not create texture from dmabuf source

**Comment by nowrep** [comment]
What GPUs do you have? Are you running OBS and the game on different GPUs?

**Comment by nowrep** [comment]
Also, is it only Vulkan capture, or also GL?

**Comment by Lepidos** [comment]
GL seems fine, tested glxgears, it works. OBS and the game are running on the same GPU. However glxgears and OBS on different GPUs doesn't.

**Comment by nowrep** [comment]
Do you get 1 or 2 planes from the GL capture when it works? And when it doesn't.

Can you please post logs from both of the cases?

**Comment by Lepidos** [comment]
**Primary GPU on OBS and glxgears:**
[obs-log_glxgears_same_gpu.txt](https://github.com/nowrep/obs-vkcapture/files/6864909/obs-log_glxgears_same_gpu.txt)

**Primary GPU on OBS and secondary GPU on glxgears:**
[obs-log_glxgears_diferent_gpu.txt](https://github.com/nowrep/obs-vkcapture/files/6864913/obs-log_glxgears_diferent_gpu.txt)


How do I know how many planes I get?

**Comment by nowrep** [comment]
Can you please try the vulkan capture with this patch:

```diff
diff --git a/src/capture.h b/src/capture.h
index 95d641e..bb5f4b7 100644
--- a/src/capture.h
+++ b/src/capture.h
@@ -29,6 +29,7 @@ with this program. If not, see <https://www.gnu.org/licenses/>
 #define DRM_FORMAT_ARGB8888 fourcc_code('A', 'R', '2', '4')
 #define fourcc_mod_code(vendor, val) ((((uint64_t)vendor) << 56) | ((val) & 0x00ffffffffffffffULL))
 #define DRM_FORMAT_MOD_INVALID fourcc_mod_code(0, ((1ULL << 56) - 1))
+#define DRM_FORMAT_MOD_LINEAR fourcc_mod_code(0, 0)
 #endif
 
 struct capture_texture_data {
diff --git a/src/vklayer.c b/src/vklayer.c
index 78f845c..b3baa56 100644
--- a/src/vklayer.c
+++ b/src/vklayer.c
@@ -597,6 +597,9 @@ static inline bool vk_shtex_init_vulkan_tex(struct vk_data *data,
                 img_info.format, &format_props);
 
         for (uint32_t i = 0; i < modifier_props_list.drmFormatModifierCount; i++) {
+            if (modifier_props[i].drmFormatModifier != DRM_FORMAT_MOD_LINEAR) {
+                continue;
+            }
             VkPhysicalDeviceImageDrmFormatModifierInfoEXT mod_info = {};
             mod_info.sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_DRM_FORMAT_MODIFIER_INFO_EXT;
             mod_info.drmFormatModifier = modifier_props[i].drmFormatModifier;

```

and then also with this one:

```diff
diff --git a/src/vklayer.c b/src/vklayer.c
index 78f845c..48e539b 100644
--- a/src/vklayer.c
+++ b/src/vklayer.c
@@ -1422,11 +1422,13 @@ static VkResult VKAPI_CALL OBS_CreateDevice(VkPhysicalDevice phy_device,
     GETADDR(GetImageSubresourceLayout);
     GETADDR(GetMemoryFdKHR);
 
+#if 0
     dfuncs->GetImageDrmFormatModifierPropertiesEXT = (PFN_vkGetImageDrmFormatModifierPropertiesEXT)
         gdpa(device, "vkGetImageDrmFormatModifierPropertiesEXT");
     if (!dfuncs->GetImageDrmFormatModifierPropertiesEXT) {
         hlog("DRM format modifier support not available");
     }
+#endif
 
 #undef GETADDR
 
```

and send the logs with each of the patch. Thanks!

**Comment by Lepidos** [comment]
Both patch fix vulkan capture
**1st patch log:**
[obs-log_vkcube_patch1.txt](https://github.com/nowrep/obs-vkcapture/files/6865250/obs-log_vkcube_patch1.txt)

++2nd patch log:**
[obs-log_vkcube_patch2.txt](https://github.com/nowrep/obs-vkcapture/files/6865255/obs-log_vkcube_patch2.txt)

**Comment by nowrep** [comment]
Can you also post log from the game process?

**Comment by Lepidos** [comment]
[vkcube-patch1.log](https://github.com/nowrep/obs-vkcapture/files/6867595/vkcube-patch1.log)
[vkcube-patch2.log](https://github.com/nowrep/obs-vkcapture/files/6867596/vkcube-patch2.log)

**Comment by nowrep** [comment]
Hmm, I really have no idea what might be wrong. If it's perhaps specific to your GPU or Mesa version.
I currently have Mesa 21.1.5 and Intel UHD 630 + RX6700XT, and it works on both GPUs.

For now, you can set the `OBS_VKCAPTURE_LINEAR=1` environment variable to make it work for you.

**Comment by Lepidos** [comment]
Ok. Thank you!
If you need me to test some more I will be happy to.

**Comment by nowrep** [comment]
It now logs available modifiers, can you please apply this patch and try each of them and tell me which ones work.
To select a modifier, set `SELECT_MODIFIER` env variable with the index, eg. `export SELECT_MODIFIER=2` to select modifier with index 2 (3rd one in the list).


```diff
diff --git a/src/vklayer.c b/src/vklayer.c
index d287fd6..771f5b0 100644
--- a/src/vklayer.c
+++ b/src/vklayer.c
@@ -607,6 +607,8 @@ static inline bool vk_shtex_init_vulkan_tex(struct vk_data *data,
                     modifier_props[i].drmFormatModifier,
                     modifier_props[i].drmFormatModifierPlaneCount);
 #endif
+            const char *s = getenv("SELECT_MODIFIER");
+            if (s && atol(s) != i) continue;
             if (vkcapture_linear && modifier_props[i].drmFormatModifier != DRM_FORMAT_MOD_LINEAR) {
                 continue;
             }

```

**Comment by Lepidos** [comment]
works if SELECT_MODIFIER >= 4

**Comment by nowrep** [comment]
Can you also post log from the game?

**Comment by Lepidos** [comment]
works:
[vkcube_SELECT_MODIFIER4.log](https://github.com/nowrep/obs-vkcapture/files/6872400/vkcube_SELECT_MODIFIER4.log)
does not work:
[vkcube_SELECT_MODIFIER3.log](https://github.com/nowrep/obs-vkcapture/files/6872398/vkcube_SELECT_MODIFIER3.log)

**Comment by AdelKS** [comment]
Hello,

After updating `obs-vkcapture` and restarting my computer, I am encountering the same issue. Should I go the same set of patches you suggested above and report back ?

Additional information:
Gentoo linux, linux 5.13.13-tkg-cfs-llvm, mesa 21.2.1, RX 5700 XT, Ryzen 5950X, obs-studio 27.0.1 (self-compiled from git)

[obs-output.txt](https://github.com/nowrep/obs-vkcapture/files/7070792/obs-output.txt)
[vkcube-output.txt](https://github.com/nowrep/obs-vkcapture/files/7070793/vkcube-output.txt)

**Comment by nowrep** [comment]
@AdelKS That's different issue. Are you sure both game and the OBS plugin are the same version?

**Comment by AdelKS** [comment]
Oh, I made sure to use `sudo xargs rm < install_manifest.txt` before updating. And I manually deleted `obs-vkcapture` executable. But it looks like I overlooked something. Thanks ! I will further investigate.

**Comment by AdelKS** [comment]
Thank you @nowrep, my issue was due to #7 where manually installing `obs-studio` puts it in a different path than the `obs-studio` installed by the packet manager. So an old version of `obs-vkcapture` was there since that issue. I will make an EBUILD so things will tracked by the package manager.

**Comment by nowrep** [comment]
@Lepidos Is this fixed now?

**Comment by Lepidos** [comment]
Yeah

**Comment by Lepidos** [comment]
I tested again  _master_ setting _OBS_VKCAPTURE_LINEAR=0_ and it works.

**Comment by nowrep** [comment]
Good to know. What's your current kernel and mesa versions?

**Comment by Lepidos** [comment]
kernel: 5.10.63
mesa: 21.2.1
