### ISSUE TITLE
Incompatible with streaming from gamescope headless backend

### ISSUE THREAD

**Issue by Lepidos** [nowrep/obs-vkcapture#221]
Steps to reproduce:

```
export OBS_VKCAPTURE=1
gamescope --backend headless -- steam
```
Then launch steam link client and navigate it to run a 64-bit game.  Screen turns black while game is running.

This issue is not present with older versions of gamescope. Like 3.12.6 or previous.

**Comment by Lepidos** [comment]
can't reproduce this anymore

**Comment by nowrep** [comment]
With gamescope you should be capturing the inner process, not gamescope itself:

    gamescope --backend headless -- env OBS_VKCAPTURE=1 steam
