### ISSUE TITLE
Does not capture flatpaks when running inside distrobox

### ISSUE THREAD

**Issue by ItsRogueRen** [nowrep/obs-vkcapture#224]
**Describe the bug**
When using OBS from a Distrobox container (i.e. Ubuntu so that you have the API log in for Twitch/YouTube/etc) obs-vkcapture is unable to capture flatpaks running outside of the distrobox. Currently trying to figure out of this is an issue with the plugin or distrobox

**Screenshots or video**
If applicable, add screenshots or video to help explain your problem.

**System (please complete the following information):**
 - OS: Nobara 40
 - GPU: AMD RX 7700XT
 - Mesa version: Mesa 24.3.0-devel
 - obs-vkcapture version: git (July 28th 2024)

**OBS log:**
```
https://pastebin.com/2wt6x3Li
```

**Game log:**
```
Paste game terminal output here.
Make sure to set OBS_VKCAPTURE_QUIET=0 environment variable.
```

**Comment by nowrep** [comment]
The OBS plugin creates abstract unix socket which the clients (games) connect to. So if you run OBS in some kind of sandbox, you need to make sure the socket is visible from outside.

**Comment by ItsRogueRen** [comment]
> The OBS plugin creates abstract unix socket which the clients (games) connect to. So if you run OBS in some kind of sandbox, you need to make sure the socket is visible from outside.

OK that would probably be a distrobox issue then, I'll have to see if there is something that can be done for that to allow it to see flatpaks

**Comment by Yasso9** [comment]
I do the opposite. I run my game in a distrobox container (archlinux), but obs is run via the client. OBS doesn't manage to capture the game. 

How can I fix this. What is the socket that should be visible, do you have more info on that ?

**Comment by fsworld009** [comment]
> I do the opposite. I run my game in a distrobox container (archlinux), but obs is run via the client. OBS doesn't manage to capture the game.
> 
> How can I fix this. What is the socket that should be visible, do you have more info on that ?

I'm running a game in distrobox (Fedora container) and running OBS on host linux via Flatpak.

I got it work by doing `sudo dnf install obs-studio-plugin-vkcapture` inside distrobox container, then run the game with `obs-gamecapture %game_launch_command%`, then the host OBS can capture it. Maybe you could achieve the same after installing the plugin in the archlinux container.

**Comment by Yasso9** [comment]
> > I do the opposite. I run my game in a distrobox container (archlinux), but obs is run via the client. OBS doesn't manage to capture the game.
> > How can I fix this. What is the socket that should be visible, do you have more info on that ?
> 
> I'm running a game in distrobox (Fedora container) and running OBS on host linux via Flatpak.
> 
> I got it working by doing `sudo dnf install obs-studio-plugin-vkcapture` inside distrobox container, then run the game with `obs-gamecapture %game_launch_command%`, then the host OBS can capture it. Maybe you could achieve the same after installing the plugin in the archlinux container.

Thanks I will try that, will get back to you if it works.
