### ISSUE TITLE
Is there way to get system installed vkcapture to work on a flatpak app.

### ISSUE THREAD

**Issue by chikenpotpi** [nowrep/obs-vkcapture#225]
The README says you can capture non flatpaks from obs flatpak, im hoping the reverse is possible.

**Comment by nowrep** [comment]
For capturing flatpak apps, you need to use https://github.com/flathub/org.freedesktop.Platform.VulkanLayer.OBSVkCapture

**Comment by chikenpotpi** [comment]
> For capturing flatpak apps, you need to use https://github.com/flathub/org.freedesktop.Platform.VulkanLayer.OBSVkCapture

Ah okay good to know, unfortunately the app im using in flatpak doesnt have vkcapture support. Hopefully they will add it soon.

**Comment by games647** [comment]
@chikenpotpi It's not required for Vulkan Games. The game can use the implicit Vulkan layer if installed and the environment variable is set.

`flatpak run --env=OBS_VKCAPTURE=1 --env=MANGOHUD=1 APP_ID` works fine for me.
