### ISSUE TITLE
Won't capture any program. Can't find library file.

### ISSUE THREAD

**Issue by SomeDudeNamedAnthony** [nowrep/obs-vkcapture#227]
**Describe the bug**
obs-gamecapture won't load because it can't find `libobs_glcapture.so`.
```log
ERROR: ld.so: object '/tmp/pressure-vessel-libs-1M12R2/${LIB}/libobs_glcapture.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
```

**Screenshots or video**
![Screenshot_20240813_011654](https://github.com/user-attachments/assets/6f386805-207f-4b1a-bcc2-6e906aeb8f5a)

**System (please complete the following information):**
 - OS: Arch Linux *(6.10.3-zen1-2-zen) (EndeavourOS rolling x86_64)*
 - GPU: AMD Radeon RX 6700 XT
 - Mesa version: Mesa 24.1.5-arch1.1
 - obs-vkcapture version: [v1.5.1](https://github.com/nowrep/obs-vkcapture/releases/tag/v1.5.1)

**OBS log:**
[*In Gist Repo*](https://gist.github.com/SomeDudeNamedAnthony/88fcbba590b0dc68de5066bd33f509ed)

**Game log:**
[*In Gist Repo*](https://gist.github.com/SomeDudeNamedAnthony/8f87987fbb3833a4751d33411abf0975
)

**Comment by nowrep** [comment]
Is garrys mod 32bit? If so, you'll have to also install 32bit package.
