### ISSUE TITLE
Question: how is capturing and encoding handled with respect to memory copies ?

### ISSUE THREAD

**Issue by AdelKS** [nowrep/obs-vkcapture#24]
Hello,

I would like to know how `obs-vkcapture` works with `obs` with respect to memory copies. Let's consider the use case of `obs` with `ffmpeg-vaapi` encoder with an AMD GPU, while capturing a vulkan game, does `obs-vkcapture` do frame copies as follows `GPU VRAM (game)` -> `RAM (obs)` -> `GPU VRAM (ffmpeg-vaapi)` ? Or does it do an in-gpu copy `GPU VRAM (game)` -> `GPU VRAM (ffmpeg-vaapi)` ? Or is it zero-copy ? I suppose zero-copy would need the use of the new `vulkan video` extensions which are not implemented in mesa nor ffmpeg yet ?

I would love to have more information on how things work, thank you !

Adel

**Comment by nowrep** [comment]
What do you mean with zero-copy? Zero-copy usually just means "no CPU copy" (eg. the data stays on GPU), not "no copy at all".
In OBS case there always needs to be at least one copy, and that's the game frame -> OBS.

There is no CPU copy in the obs-vkcapture code, it's: GPU -> GPU copy of game frame and then the buffer is passed to OBS where it gets imported as texture, with no additional copies. What OBS does with the texture afterwards is another thing.

Default OBS VAAPI encoder always does CPU copy. If you want zero-copy encoder, you can try the StreamFX AMF encoder. VAAPI can do zero-copy just fine, it's the OBS implementation that doesn't support it.

But from my testing, the performance of OBS VAAPI vs StreamFX AMF is exactly the same. So perhaps my testing was wrong (?), or the copy is non-issue.
I tested it with a game where I would get 120fps (full GPU utilization) without capture, and both encoders resulted in 5fps loss.

But I don't normally use the AMD GPU for encoding, I let my Intel GPU do it.

**Comment by AdelKS** [comment]
Thank you for the information. I was expecting some kind of optimization where if a unique source covers the entire output pane of OBS, it wouldn't to do compositing of various sources and not even do GPU-GPU copy and just encode from the source directly: I heard that OBS on Windows does something similar ? and I thought that was what we meant by "zero-copy".

> Default OBS VAAPI encoder always does CPU copy. If you want zero-copy encoder, you can try the StreamFX AMF encoder. VAAPI can do zero-copy just fine, it's the OBS implementation that doesn't support it.

Very interesting information, thank you. I wanted to know more about these kind of things.

> But from my testing, the performance of OBS VAAPI vs StreamFX AMF is exactly the same. So perhaps my testing was wrong (?), or the copy is non-issue.

I think given enough cores, the copy isn't that bad. But for people with limited resources like an i3 with 2c/4t CPU copy makes a huge difference when a game is running too.

> But I don't normally use the AMD GPU for encoding, I let my Intel GPU do it.

Using the iGPU must be best in terms of effect on the game performance, who's running on the other GPU.

**Comment by nowrep** [comment]
> I was expecting some kind of optimization where if a unique source covers the entire output pane of OBS, it wouldn't to do compositing of various sources and not even do GPU-GPU copy and just encode from the source directly: I heard that OBS on Windows does something similar ? and I thought that was what we meant by "zero-copy".

I have no idea how Windows screen capture works, but it seems unlikely to me it would work like that.
There's also no shortcut like that in OBS, it will always render the scene into a texture, does color conversion to NV12 and then it gets passed to encoder, either as a texture directly or as downloaded image data.

> I think given enough cores, the copy isn't that bad. But for people with limited resources like an i3 with 2c/4t CPU copy makes a huge difference when a game is running too.

Well, you can do your tests and see what works best for you :)

**Comment by AdelKS** [comment]
Thanks for your help and information.

**Comment by AdelKS** [comment]
@nowrep Is streamFX AMF any different from FFMPEG-AMF with AMDGPU-PRO ? Or do I need to use https://github.com/xaymar/obs-streamfx ?

**Comment by nowrep** [comment]
You need ffmpeg with `--enable-amf`+ amdgpu-pro and use the encoder from StreamFX afaik. You can find more info on the StreamFX wiki.

**Comment by AdelKS** [comment]
Thank you very much for the information!
