### ISSUE TITLE
Take my money?

### ISSUE THREAD

**Issue by Hubro** [nowrep/obs-vkcapture#26]
I just found this plugin via Google after being frustrated about getting stutters while gaming with Pipewire screen capture.

Took me about 30 seconds to install [the AUR package](https://aur.archlinux.org/pkgbase/obs-vkcapture-git/) and it worked **immediately**. I'm capturing 60 FPS at perfect quality while still getting a buttery smooth 200 FPS ingame and no stutters. I've only been playing with this for half an hour or so but so far nothing has crashed :crossed_fingers: 

It blows my mind that this is possible in Linux now!

For how insanely awesome this plugin is I think it's criminally undersupported. Have you considered making it possible to sponsor this project via [GitHub Sponsors](https://github.com/sponsors)? Or alternatively, set up a Paypal donation link? I feel bad using this plugin for free.

**Comment by nowrep** [comment]
I don't ask for money, so there is no donation link.

My PayPal is david@rosca.cz if you want, but you really don't have to, it's fine :) I'm glad you like it, and that's enough.

**Comment by Hubro** [comment]
I've used this project for well over a year now. It's one of the most amazing open source projects I know of. I'm playing World of Warcraft at 2560x1440 200 FPS while recording at 120 FPS with OBS, the effect of the screen recording is completely imperceptible. It also works flawlessly together with MangoHud. It also effortlessly handles me resizing the game window on the fly. It's mind blowing how stable it is and how well it performs.

I feel bad using software this awesome without contributing anything back to the author, and I'm sure other people feel the same. I really think you should apply for Github Sponsorship on this project, and/or publish some way for people to throw a coin in your hat, such as https://ko-fi.com or Patreon.

![image](https://user-images.githubusercontent.com/597206/166827696-089a7fc4-a7eb-405a-9302-f560cf080d07.png)

**Comment by nowrep** [comment]
Thanks for your support!

I don't really think github sponsorship/patreon would be worth it.
First of all, the project is really small (it's at only 160 github stars now). It's also mostly finished now, I don't spend almost any time on it anymore - everything I wanted it to do it now does. It works perfectly for me, and I am happy it does for you too :)

Maybe now with the new nvidia drivers it will get some new users, but I don't expect the "growth rate" to change that much.
