### ISSUE TITLE
Plans to provide a higher level user experience?

### ISSUE THREAD

**Issue by Hubro** [nowrep/obs-vkcapture#27]
If this plugin aimed to match the ease-of-use of "Game capture" in Windows, it would start recording for all games by default (Vulkan and OpenGL) and present a dropdown menu in the "Game capture" source in OBS to pick a game.

Currently this addon is amazing, but to gain more mainstream usage it would probably (?) need to be even simpler to set up and use. At some point it might even be bundled with OBS by default :crossed_fingers: 

Is this on the roadmap, or is it out of scope for this project?

**Comment by nowrep** [comment]
For Vulkan, you can set OBS_VKCAPTURE=1 environment variable (eg. in your `~/.profile`) and it will be used for all Vulkan apps, same as on Windows. But then there is an issue where multiple running applications will try to connect to the OBS plugin, and you can't select which one to use because there is currently no support for capturing multiple games. But even if/when this is implemented, I still don't think loading the layer for all apps unconditionally is a good idea.

For OpenGL it's not really feasible, as it would mean setting global LD_PRELOAD.

**Comment by Hubro** [comment]
How is all this done on Windows? Pretty much all games (Direct3D, OpenGL, Vulkan) can be captured by OBS without doing any setup beforehand. Is it possible to do anything similar in Linux?

**Comment by nowrep** [comment]
I don't know how the OpenGL is done, but Vulkan is exactly the same as on Linux. They just load the Vulkan layer to all Vulkan apps.

**Comment by galvertez** [comment]
@nowrep would i be able to use `OBS_VKCAPTURE=1` in the steam launch options of a game, so that only that game will attempt to connect to obs?

**Comment by nowrep** [comment]
@galvertez Yes, you can use either `OBS_VKCAPTURE=1 %command%` or `obs-vkcapture %command%` for Steam.

**Comment by nowrep** [comment]
You can now select which window to capture, so you can just set the Vulkan layer to be loaded for all Vulkan apps and it should work just like on Windows.

```sh
echo "export OBS_VKCAPTURE=1" > /etc/profile.d/obs-vkcapture.sh
```

**Comment by Hubro** [comment]
> You can now select which window to capture, so you can just set the Vulkan layer to be loaded for all Vulkan apps and it should work just like on Windows.
> 
> ```shell
> echo "export OBS_VKCAPTURE=1" > /etc/profile.d/obs-vkcapture.sh
> ```

Dude, that's awesome! :grin: And it remembers the selection between sessions, which is perfect! This is a huge UX improvement.

I have a couple of questions:

- The "empty" choice at the top, does it basically mean "Auto"? Should it perhaps say "Auto" rather than be empty?

  ![image](https://user-images.githubusercontent.com/597206/128843784-01bf9332-9cb8-45b4-9adc-ac546ed3d5da.png)
- How does it get the window name? In this case, World of Warcraft becomes "wine64-preloader". This is how the process tree looks:

  ![image](https://user-images.githubusercontent.com/597206/128844131-1c71e22d-f7c8-4ab3-b4a8-a52c9d8cc80c.png)

  In this case I would expect the window name to either be "WoWClassic.exe" (the name of the process) or "World of Warcraft", the name of the Wayland window.

  The "optimal" solution would be if the recorder could check the process tree and detect that the game is a child process of "lutris-wrapper" (because the game was launched by [Lutris](https://lutris.net), then grab the game name from there. (In this case, "World of Warcraft (Classic)".) I assume something similar could be done for Steam.

**Comment by nowrep** [comment]
> The "empty" choice at the top, does it basically mean "Auto"? Should it perhaps say "Auto" rather than be empty?

Yes, I think it's like that in the Windows plugin too?

> How does it get the window name? In this case, World of Warcraft becomes "wine64-preloader". This is how the process tree looks:

It's just a name of the executable, I need to add special handling for wine.

**Comment by Hubro** [comment]
> > The "empty" choice at the top, does it basically mean "Auto"? Should it perhaps say "Auto" rather than be empty?
> 
> Yes, I think it's like that in the Windows plugin too?

Possibly, but it's not very intuitive. Here's an opportunity to be better than the Windows counterpart 😁
