### ISSUE TITLE
[Request] Show cursor (mouse pointer)

### ISSUE THREAD

**Issue by Sethox** [nowrep/obs-vkcapture#28]
The request is about capture the cursor when the cursor invades the canvas of the game-capture if it's possible.

Otherwise it's a solid plugin and thank you for it.

**Comment by nowrep** [comment]
There is a cursor support on X11. If you use Wayland and play games in XWayland then you can start OBS on XWayland too and it'll work.

    OBS_USE_EGL=1 obs --platform xcb

If you are playing Wayland native game, then unfortunately it's not possible. There was some work on a Wayland protocol that would allow this, but don't expect it to be ready anytime soon.
