### ISSUE TITLE
Capturing Blender 2.92 and newer works strange

### ISSUE THREAD

**Issue by scaledteam** [nowrep/obs-vkcapture#29]
Hi. Thank you for your plugin, with supported games it works great! I tried to capture Blender 2.92, 2.93, but got only some part of interface on screen. Blender 2.90 works fine. Can you help me to fix this strange capture artifacts?

P.S. Cmake 3.19 is necessary? I successfully compiled it with 3.18 on Debian 11.

![Screenshot 2021-08-08 18-10-36](https://user-images.githubusercontent.com/43995399/128669427-8be4ab51-61d9-4e67-9b3e-dfcb6b5678a6.png)
![Screenshot 2021-08-08 18-11-04](https://user-images.githubusercontent.com/43995399/128669430-02950e51-8691-4e4e-ac92-7e16fbe11d0f.png)

**Comment by nowrep** [comment]
OpenGL capture is kinda "fragile", so it's hit or miss right now if it's going to work, unfortunately.

> P.S. Cmake 3.19 is necessary? I successfully compiled it with 3.18 on Debian 11.

In older versions `FindX11.cmake` won't find all required XCB libs. You will be able to build with older CMake, but you won't get cursor support.
