### ISSUE TITLE
OBS-VKCapture doesnt shows up as source in OBS

### ISSUE THREAD

**Issue by plasticbomb1986** [nowrep/obs-vkcapture#31]
1starting the game, i see obs-vkcapture init and injecting two extension, starting obs i see its loading linux-vkcapture.so, but in obs i cant select the option as source, because its not showing up.

![Screenshot from 2021-08-14 16-36-35](https://user-images.githubusercontent.com/26345407/129449901-ccf52ba2-8e47-479f-b502-af0647152df4.png)

Any idea where it might get struck?

**Comment by nowrep** [comment]
Run obs with OBS_USE_EGL env var set to 1: `OBS_USE_EGL=1 obs`
