### ISSUE TITLE
Running a game with obs-glcapture in a Window breaks drawing

### ISSUE THREAD

**Issue by Krutonium** [nowrep/obs-vkcapture#34]
If you run a game like Stardew Valley or Rimworld in a Window, having run it with `obs-glcapture` and then move the Window, it visually breaks with a result similar to [this](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi.stack.imgur.com%2FEA0H8.jpg&f=1&nofb=1)

I'm running the games on the Intel card of an Optimus Laptop 

Intel HD 4600
nVidia GTX 950M
i7 4720HQ
12GB RAM
Arch Linux
Gnome

**Comment by Krutonium** [comment]
![image](https://user-images.githubusercontent.com/3945538/130054419-d599fe90-a80d-4c49-a77a-7901693d9d1d.png)

**Comment by nowrep** [comment]
Is this with current `master`?

**Comment by Krutonium** [comment]
Assuming that's what is being pulled with the `-git` package, then yes.

**Comment by Krutonium** [comment]
You may have to run the game Fullscreen then switch it to a Window for it to happen.

**Comment by nowrep** [comment]
For me it just crashes :D GL capture with 32 bit apps seems to be broken.

**Comment by Krutonium** [comment]
In fairness it does capture perfectly fine - It's just super broken for the Window itself on my system lol.

**Comment by nowrep** [comment]
That's interesting.
Are you running it with Wine and it is a 32bit application, correct?
Are you on Wayland (running in XWayland) or on X11?

Also can you please try again now, with current master?

**Comment by Krutonium** [comment]
Actually both games are native, so far as I know! As for their bit-ness, I believe they're both 64 bit.

I'm running on x11 throughout.

Will do

**Comment by Krutonium** [comment]
Nope, still does it on latest master.

**Comment by Krutonium** [comment]
Okay so exact reproduction:

Have OBS Open and Capturing, recording not required

The Window needs to either start fullscreen, or be made fullscreen. 
Then toggle the game into a Window and move it. It will do this, so long as OBS is actively capturing. If OBS is not capturing then it's fine.

**Comment by nowrep** [comment]
Well, I don't have those games (at least, the Linux versions) so I can't really test it myself.
I assume the game is frozen when this happens, or is the window contents updating?
Can you please upload log from the game process?

**Comment by Krutonium** [comment]
Nope, the game stays perfectly functional, well, at least the parts of it I can see! 

How can I make said log?

**Comment by nowrep** [comment]
`obs-glcapture your-game-binary &> out.log`

**Comment by Krutonium** [comment]
The entire log is
```
[krutonium@krutonium-laptop RimWorld]$ cat out.log 
Set current directory to /mnt/Steam/SteamLibrary/steamapps/common/RimWorld
Found path: /mnt/Steam/SteamLibrary/steamapps/common/RimWorld/RimWorldLinux
[obs-vkcapture] Init GLX 0.9.1
```

**Comment by Krutonium** [comment]
On Stardew Valley instead:
```
[krutonium@krutonium-laptop Stardew Valley]$ cat out.log 
Please use SDL 2.0.5 or higher.
[obs-vkcapture] Init GLX 0.9.1
NoFpsCap: This feature is not available
setGameMode( 'titleScreenGameMode (0)' )
loadPreferences(); begin - languageCode=en
savePreferences(); async=False, languageCode=en
[S_API] SteamAPI_Init(): Loaded '/home/krutonium/.local/share/Steam/linux64/steamclient.so' OK.
Setting breakpad minidump AppID = 413150
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198107443647 [API loaded no]
Steam logged on: True
Initializing GalaxySDK
Requesting Steam app ticket
loadPreferences(); begin - languageCode=en
savePreferences(); async=False, languageCode=en
Window_ClientSizeChanged(); Window.ClientBounds={X:560 Y:275 Width:1280 Height:720}
Signing into GalaxySDK
Galaxy auth success
Galaxy signed in
Galaxy logged on
loadPreferences(); begin - languageCode=en
savePreferences(); async=False, languageCode=en
savePreferences(); async=False, languageCode=en
Window_ClientSizeChanged(); Window.ClientBounds={X:0 Y:0 Width:1920 Height:1080}
loadPreferences(); begin - languageCode=en
savePreferences(); async=False, languageCode=en
savePreferences(); async=False, languageCode=en
Window_ClientSizeChanged(); Window.ClientBounds={X:0 Y:0 Width:1280 Height:720}
[obs-vkcapture] Texture GL_RGBA 1280x720
[obs-vkcapture] ------------------ opengl capture started ------------------
loadPreferences(); begin - languageCode=en
savePreferences(); async=False, languageCode=en
savePreferences(); async=False, languageCode=en
Window_ClientSizeChanged(); Window.ClientBounds={X:0 Y:0 Width:1920 Height:1080}
[obs-vkcapture] ------------------- opengl capture freed -------------------
[obs-vkcapture] Texture GL_RGBA 1920x1080
[obs-vkcapture] ------------------ opengl capture started ------------------
loadPreferences(); begin - languageCode=en
savePreferences(); async=False, languageCode=en
savePreferences(); async=False, languageCode=en
Window_ClientSizeChanged(); Window.ClientBounds={X:0 Y:0 Width:1280 Height:720}
[obs-vkcapture] ------------------- opengl capture freed -------------------
[obs-vkcapture] Texture GL_RGBA 1280x720
[obs-vkcapture] ------------------ opengl capture started ------------------
loadPreferences(); begin - languageCode=en
savePreferences(); async=False, languageCode=en
savePreferences(); async=False, languageCode=en
Window_ClientSizeChanged(); Window.ClientBounds={X:0 Y:0 Width:1920 Height:1080}
[obs-vkcapture] ------------------- opengl capture freed -------------------
[obs-vkcapture] Texture GL_RGBA 1920x1080
[obs-vkcapture] ------------------ opengl capture started ------------------
loadPreferences(); begin - languageCode=en
savePreferences(); async=False, languageCode=en
savePreferences(); async=False, languageCode=en
Window_ClientSizeChanged(); Window.ClientBounds={X:0 Y:0 Width:1280 Height:720}
[obs-vkcapture] ------------------- opengl capture freed -------------------
[obs-vkcapture] Texture GL_RGBA 1280x720
[obs-vkcapture] ------------------ opengl capture started ------------------
Disconnected: ClosedGame
./StardewValley: line 38: 423367 Killed                  LC_ALL="C" ./StardewValley.bin.x86_64 $@
```

**Comment by Krutonium** [comment]
1280x720 is when it was made Windowed, 1920x1080 is toggling fullscreen.

**Comment by nowrep** [comment]
There's really nothing that looks "wrong". I'm out of ideas, unfortunately.
Unless you can reproduce it also in some other game that I can run myself (preferably free to download), that's it for now.

**Comment by Krutonium** [comment]
I'll see what I can find.

**Comment by Krutonium** [comment]
What games *do* you own?

**Comment by nowrep** [comment]
Native Linux OpenGL games? supertuxkart, I guess...

**Comment by nowrep** [comment]
Is this still happening?

**Comment by Krutonium** [comment]
I havn't used this in ages :|

**Comment by nowrep** [comment]
Please reopen if this is still happening.
