### ISSUE TITLE
Provide SONAME for libVkLayer_obs_vkcapture.so and libobs_glcapture.so

### ISSUE THREAD

**Issue by AdelKS** [nowrep/obs-vkcapture#37]
Hello,

I made a Gentoo ebuild for this awesome project, in [GURU](https://github.com/gentoo/guru/tree/dev/media-video/obs-vkcapture) (you can update the README to mention it if you are good with that), and I get a QA notice about two libraries:

```shell
 * QA Notice: The following shared libraries lack a SONAME
 * /usr/lib64/libVkLayer_obs_vkcapture.so
 * /usr/lib64/libobs_glcapture.so
```

When manually installed with the instructions in the README, these files also find themselves at the same directory, here's what's in the `install_manifest.txt`

```txt
/usr/lib/libVkLayer_obs_vkcapture.so
/usr/lib/libobs_glcapture.so
```

[The documentation](https://dev.gentoo.org/~zmedico/portage/doc/ch07s04.html) about this QA notice seem to either suggest providing a SONAME for these libraries, or they actually are at the wrong place, since they're installed in a shared location, and need to be in `/usr/lib64/obs-plugins/` instead ?

Thanks!

Adel

**Comment by nowrep** [comment]
There is no need for SONAME since nothing links against these libraries. They are used just as a "plugin".
You can move the Vulkan library anywhere you want, as long as you update the paths in the layer file (json). You can't easily move the OpenGL library.

**Comment by AdelKS** [comment]
The Gentoo QA seems to say this about plugins

> Note that this warning only applies to shared libraries that you would link against. It certainly does not apply to plugins that you would dynamically load. However, plugins should not exist in the main library directory, but rather an application specific subdirectory in the library directory. In other words, it should be /usr/lib/app/plugin.so rather than /usr/lib/plugin.so. 

Anyway, I only wanted to bring this to your attention, you can close the issue if you do not plan on doing anything about it.

Thanks!

**Comment by nowrep** [comment]
Where does this package installs the libraries? https://packages.gentoo.org/packages/media-libs/vulkan-layers
On Arch it gets installed to `/usr/lib`, and I don't really see any problem with that.

**Comment by AdelKS** [comment]
They are installed at the same place

```shell
➜  ~ equery files vulkan-layers | grep .so
/usr/lib/libVkLayer_khronos_validation.so
/usr/lib64/libVkLayer_khronos_validation.so
```

But they provide a SONAME and the QA notice does not get triggered

```shell
➜  ~ objdump -p /usr/lib/libVkLayer_khronos_validation.so | grep SONAME
  SONAME               libVkLayer_khronos_validation.so
➜  ~ objdump -p /usr/lib64/libVkLayer_khronos_validation.so | grep SONAME
  SONAME               libVkLayer_khronos_validation.so
```

Although they do not have a version, so not useful anyway ? I checked the ebuild, and the soname is not enforced, it looks like it's setup upstream.

Adel
