### ISSUE TITLE
Optimus laptop

### ISSUE THREAD

**Issue by Leeo97one** [nowrep/obs-vkcapture#5]
Is obs-vkcapture supposed to work on Optimus (Intel+NVIDIA) laptop? I tried on mine but I fail to capture anything when the application is rendered on the NVIDIA GPU:
```
$ obs-vkcapture vkcube
[obs-vkcapture] Init 0.4
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

Selected GPU 1: GeForce GTX 1050, type: 2
[obs-vkcapture] Injecting VK_KHR_external_memory_fd extension
[obs-vkcapture] GetMemoryFdKHR failed -3
[obs-vkcapture] ------------------- vulkan capture freed -------------------
[obs-vkcapture] vk_shtex_init failed
```
```
$ obs-glcapture eglgears_x11
EGL_VERSION = 1.5
[obs-vkcapture] Init 0.4
[obs-vkcapture] Failed to query dmabuf export
[obs-vkcapture] shtex init failed
[obs-vkcapture] ------------------- opengl capture freed -------------------
[obs-vkcapture] gl_init failed
[obs-vkcapture] Failed to query dmabuf export
[obs-vkcapture] shtex init failed
[obs-vkcapture] ------------------- opengl capture freed -------------------
[obs-vkcapture] gl_init failed
[...]
```
```
$ obs-glcapture glxgears
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
[obs-vkcapture] Init 0.4
[obs-vkcapture] Failed to get buffer from pixmap
[obs-vkcapture] shtex init failed
[obs-vkcapture] ------------------- opengl capture freed -------------------
[obs-vkcapture] gl_init failed
[obs-vkcapture] Failed to get buffer from pixmap
[obs-vkcapture] shtex init failed
[obs-vkcapture] ------------------- opengl capture freed -------------------
[obs-vkcapture] gl_init failed
[...]
```

Packages used on Arch Linux:
- obs-vkcapture-git r48.091a0e9-1
- obs-studio-git 26.1.2.r290.ga52012e8c-1

OBS Studio logs: [2021-03-30 16-07-47.txt](https://github.com/nowrep/obs-vkcapture/files/6229727/2021-03-30.16-07-47.txt)

**Comment by nowrep** [comment]
Actually I am not sure if this is Optimus specific or just NVIDIA proprietary driver not supporting the required extensions to get dmabuf from vkmemory/eglimage/xpixmap.
I've only myself tested it on AMD.

**Comment by Leeo97one** [comment]
@arrowgent So it works for you? You are able to capture a NVIDIA-rendered application on your Optimus laptop using obs-vkcapture?

**Comment by danyeet** [comment]
I tried a few days ago explicitly with the nvidia gpu and I just got dmabuf errors. Pretty sure there is missing driver support but if I am wrong please correct me. Also the [https://www.phoronix.com/scan.php?page=news_item&px=NVIDIA-470-Wayland-Friendly](upcoming 470 driver) might fix it so be on the lookout. I got it working though with the intel gpu and it was running just fine.

**Comment by nowrep** [comment]
It requires `VK_EXT_external_memory_dma_buf` which is currently unsupported in NVIDIA proprietary driver.

**Comment by SmashleyG** [comment]
I am assuming my issues is the same. output complains about: 

[obs-vkcapture] missing device extension: VK_EXT_external_memory_dma_buf

I have:
CPU: AMD 1920x Threadripper
GPU: nvidia rtx 3080 with nvidia drivers 460.73.01
Distro: PopOs 20.10

**Comment by nowrep** [comment]
Should be working now with 515.43.04 driver.
