### ISSUE TITLE
obs-vkcapture doesn't work with 32bit games

### ISSUE THREAD

**Issue by DoomPenguin9** [nowrep/obs-vkcapture#52]
obs-vkcapture works great with every 64bit game I've tried, but it doesn't work with any 32bit game. I'm not sure what has gone wrong, since I used the AUR package to install obs-vkcapture, which should install everything correctly.

The games I am trying to record are Far Cry 3, Call Of Duty Modern Warfare 3, and Call ff Duty Black Ops 2.

System:
OS: Arch Linux
Kernel: 5.15.12-zen1-1-zen
GPU: RX 6700XT
Mesa 22.0.0-devel (git-f43b0d5cdc)
OBS version: obs-studio 27.1.3-3

**Comment by nowrep** [comment]
Do you really have the 32bit package installed?

`pacman -Ql lib32-obs-vkcapture-git`
