### ISSUE TITLE
obs-vkcapture doesn't capture MangoHUD and vkBasalt

### ISSUE THREAD

**Issue by DoomPenguin9** [nowrep/obs-vkcapture#53]
obs-vkcapture captures the game without the effects applied by vkBasalt or MangoHUDs overlay. It used to capture those, but after a system update it stopped.

**System**

OS: Arch Linux
Kernel: 5.16.0-zen1-1-zen
xorg-server 21.1.3-1
Mesa version: Mesa 22.0.0-devel (git-307cdb7147)
obs-vkcapture(AUR package) version: obs-vkcapture-git r176.f8a6a71-1

**Comment by nowrep** [comment]
Same as #14
