### ISSUE TITLE
obs-vkcapture doesn't capture colours correctly in some cases

### ISSUE THREAD

**Issue by DoomPenguin9** [nowrep/obs-vkcapture#54]
In some cases, obs-vkcapture does not capture colours correctly. A good example is Call Of Duty: Black Ops 2, where vkcapture captures this image
![2022-01-14_19-36](https://user-images.githubusercontent.com/85156713/149639442-4f3e241a-0122-47dd-b7c2-350144667547.png)
when this is what is actually on my screen
![2022-01-15_22-25](https://user-images.githubusercontent.com/85156713/149639560-ae239c31-7154-4df9-9b5b-18e813948e1d.png)

A similar issue appears in DOOM Eternal with vkBasalt. To get vkcapture to load after vkBasalt, so that it actually captures the image with the effect applied, I launch the game with
`VK_INSTANCE_LAYERS=VK_LAYER_vkbasalt:VK_LAYER_OBS_vkcapture_64`
which results in vkcapture capturing this image
![2022-01-14_16-36](https://user-images.githubusercontent.com/85156713/149639627-a687d841-38df-4f1d-b53a-c0b8b4186b7e.png)
when this is what is actually on my screen
![2022-01-14_16-31](https://user-images.githubusercontent.com/85156713/149639637-fa62ae07-9624-4175-ad60-44935251f3a8.png)

**Comment by nowrep** [comment]
Can you please share full vkbasalt config so I can test it myself? Also please upload logs from the game (only the lines with obs-vkcapture are important).

**Comment by DoomPenguin9** [comment]
> Can you please share full vkbasalt config so I can test it myself? Also please upload logs from the game (only the lines with obs-vkcapture are important).

Here is the vkBasalt.conf with the LUT used: 
[vkBasalt.tar.gz](https://github.com/nowrep/obs-vkcapture/files/7877533/vkBasalt.tar.gz)

The part of the log that mentions vkcapture is this:

17:27:20.939: [linux-vkcapture] Creating texture from dmabuf 2560x1440 modifier:144115188488387331
17:27:20.939: [linux-vkcapture]  [0] fd:9 stride:10240 offset:0
17:27:20.939: [linux-vkcapture]  [1] fd:10 stride:2560 offset:15728640
17:28:47.004: [linux-vkcapture] Creating texture from dmabuf 2560x1440 modifier:144115188488387331
17:28:47.004: [linux-vkcapture]  [0] fd:9 stride:10240 offset:0
17:28:47.004: [linux-vkcapture]  [1] fd:10 stride:2560 offset:15728640
17:29:09.796: [linux-vkcapture] Creating texture from dmabuf 2560x1440 modifier:144115188488387331
17:29:09.796: [linux-vkcapture]  [0] fd:11 stride:10240 offset:0
17:29:09.796: [linux-vkcapture]  [1] fd:38 stride:2560 offset:15728640
17:30:11.301: [linux-vkcapture] Creating texture from dmabuf 2560x1440 modifier:144115188488387331
17:30:11.301: [linux-vkcapture]  [0] fd:9 stride:10240 offset:0
17:30:11.301: [linux-vkcapture]  [1] fd:10 stride:2560 offset:15728640

**Comment by nowrep** [comment]
I've tried your vkbasalt config, but it "works" fine (as in, it is exactly the same dark image on screen and in OBS).

**Comment by DoomPenguin9** [comment]
> I've tried your vkbasalt config, but it "works" fine (as in, it is exactly the same dark image on screen and in OBS). Does it happen in any game with this config? Maybe can you also try just with `vkcube`?
I think the image on your screen is dark because there are some extra settings in the .fx files I forgot to add to my original 

comment, sorry about that. The settings are:
in Curves.fx you need :
ui_tooltip = "The amount of contrast you want.";
> = 0.05;

in FakeHDR.fx you need

uniform float HDRPower < __UNIFORM_SLIDER_FLOAT1
	ui_min = 0.0; ui_max = 8.0;
	ui_label = "Power";
> = 1.20;
uniform float radius1 < __UNIFORM_SLIDER_FLOAT1
	ui_min = 0.0; ui_max = 8.0;
	ui_label = "Radius 1";
> = 0.793;
uniform float radius2 < __UNIFORM_SLIDER_FLOAT1
	ui_min = 0.0; ui_max = 8.0;
	ui_label = "Radius 2";
	ui_tooltip = "Raising this seems to make the effect stronger and also brighter.";
> = 0.90;

You just need to change the numbers in the .fx files.

The issue described above happens in every game with this preset, yes. Also, the Black Ops 2(first image in my original comment) image was taken with no vkBasalt, so there are colour issues in games with no vkBasalt. So far, Black Ops 2 is the only game I've seen that has this issue and if I see this happening in other, I'll report them here.

**Comment by nowrep** [comment]
I've changed the shader values and the image is not dark anymore, but of course it made no difference. The image is identical both on screen and in OBS (preview and in actual capture).

Can you please show terminal output of vkcube?

**Comment by DoomPenguin9** [comment]
> I've changed the shader values and the image is not dark anymore, but of course it made no difference. The image is identical both on screen and in OBS (preview and in actual capture).
> 
> Can you please show terminal output of vkcube (not output from OBS)?
> 
> I can't test it with Black Ops 2 because I don't own the game.

Running `VK_INSTANCE_LAYERS=VK_LAYER_vkbasalt:VK_LAYER_OBS_vkcapture_64 ENABLE_VKBASALT=1 VKBASALT_CONFIG_FILE=/home/penguin/.steam/steam/steamapps/common/DOOMEternal/vkBasalt.conf obs-vkcapture vkcube` to start vkcube with vkBasalt and vkcapture gives the following output:

[obs-vkcapture] Init Vulkan 1.1.1
vkBasalt info:  config file: /home/penguin/.steam/steam/steamapps/common/DOOMEternal/vkBasalt.conf
vkBasalt info:  effects = colorfulness:hdr:contrast:lut
vkBasalt info:  lutFile = /home/penguin/.steam/steam/steamapps/common/DOOMEternal/lut.png
vkBasalt info:  colorfulness = /home/penguin/reshade-shaders-master/Shaders/Colourfulness.fx
vkBasalt info:  hdr = /home/penguin/reshade-shaders-master/Shaders/FakeHDR.fx
vkBasalt info:  contrast = /home/penguin/reshade-shaders-master/Shaders/Curves.fx
vkBasalt info:  reshadeTexturePath = /home/penguin/reshade-shaders-master/Textures
vkBasalt info:  reshadeIncludePath = /home/penguin/reshade-shaders-master/Shaders
Selected GPU 0: AMD RADV NAVY_FLOUNDER, type: 2
[obs-vkcapture] Injecting VK_KHR_external_memory_fd extension
[obs-vkcapture] Injecting VK_EXT_image_drm_format_modifier extension
[obs-vkcapture] Texture VK_FORMAT_B8G8R8A8_UNORM 1266x1385
[obs-vkcapture] ------------------ vulkan capture started ------------------
[obs-vkcapture] ------------------- vulkan capture freed -------------------

The result is this
![2022-01-17_20-25](https://user-images.githubusercontent.com/85156713/149833626-129dea11-d7ca-45d2-850f-25ecb3c2b639.png)

**Comment by DoomPenguin9** [comment]
Ok, so I figured it out. In the scene I have set up for recording, I had the option "allow transparency" enabled in the game capture source. It appears that this messes with 100% of games that use I vkBasalt in, and a number of games that I don't use vkBasalt in. Disabling that fixed the issue.

**Comment by nowrep** [comment]
Alright, that makes sense.
