### ISSUE TITLE
i cant do cmake

### ISSUE THREAD

**Issue by driver248** [nowrep/obs-vkcapture#55]
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Vulkan (missing: Vulkan_LIBRARY Vulkan_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindVulkan.cmake:71 (find_package_handle_standard_args)
  CMakeLists.txt:6 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/semen/Загрузки/obs-vkcapture-master/build/CMakeFiles/CMakeOutput.log".

**Comment by nowrep** [comment]
You need to install vulkan dev package.
