### ISSUE TITLE
libVkLayer_obs_vkcapture.so returns 0 strides size

### ISSUE THREAD

**Issue by nm004** [nowrep/obs-vkcapture#59]
### Summary

Game Capture pliugin cannot create texture and show black image because `libVkLayer_obs_vkcapture.so` returns 0  strides size of image on Intel UHD 770 when using `VK_IMAGE_TILING_DRM_FORMAT_MODIFIER_EXT` tiling. I could solve the issue by compelling `img_info.tiling = VK_IMAGE_TILING_LINEAR` (with OBS_VKCAPTURE_LINEAR switch, but some rework was needed). Please check out PR #58.

### Issue detail

Vulkan-based program cannot be captured on Intel UHD 770. It returns 0 strides size when using DRM modifier support and it says, `error: Cannot create EGLImage: EGL cannot access a requested resource (for example a context is bound in another thread).`. See the following output of the program.

OBS's linux-vkcapture output:
```
info: [linux-vkcapture] plugin loaded successfully (version 1.1.1)
info: [linux-vkcapture] Creating texture from dmabuf 1280x720 modifier:72057594037927938
info: [linux-vkcapture]  [0] fd:47 stride:0 offset:0
error: Cannot create EGLImage: EGL cannot access a requested resource (for example a context is bound in another thread).
error: [linux-vkcapture] Could not create texture from dmabuf source
```

Captured program's obs-vkcapture output:
```
[obs-vkcapture] Init Vulkan 1.1.1
[obs-vkcapture] CreateInstance
[obs-vkcapture] CreateInstance VK_SUCCESS
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

[obs-vkcapture] CreateDevice
[obs-vkcapture] Injecting VK_KHR_external_memory_fd extension
[obs-vkcapture] Injecting VK_EXT_image_drm_format_modifier extension
[obs-vkcapture] CreateDevice VK_SUCCESS
[obs-vkcapture] CreateXcbSurfaceKHR
[obs-vkcapture] CreateSwapchainKHR VK_SUCCESS
[obs-vkcapture] GetSwapchainImagesKHR VK_SUCCESS
[obs-vkcapture] GetSwapchainImagesKHR VK_SUCCESS
[obs-vkcapture] Texture VK_FORMAT_B8G8R8A8_UNORM 1280x720
[obs-vkcapture] Available modifiers:
[obs-vkcapture]  0: modifier:0 planes:1
[obs-vkcapture]  1: modifier:72057594037927937 planes:1
[obs-vkcapture]  2: modifier:72057594037927938 planes:1
[obs-vkcapture] Got planes 1 fd 12
[obs-vkcapture] Got modifier 72057594037927938
[obs-vkcapture] ------------------ vulkan capture started ------------------
[obs-vkcapture] CreateCommandPool VK_SUCCESS
[obs-vkcapture] AllocateCommandBuffers VK_SUCCESS
[obs-vkcapture] CreateFence VK_SUCCESS
...
[obs-vkcapture] BeginCommandBuffer VK_SUCCESS
[obs-vkcapture] QueueSubmit VK_SUCCESS
[obs-vkcapture] DestroySwapchainKHR
[obs-vkcapture] ------------------- vulkan capture freed -------------------
[obs-vkcapture] DestroySurfaceKHR
[obs-vkcapture] DestroyDevice
[obs-vkcapture] DestroyInstance
```
#### Test environment

Commit: [29fb16ffafde962b1771966def2f50a3dbcb4b39](https://github.com/nowrep/obs-vkcapture/tree/29fb16ffafde962b1771966def2f50a3dbcb4b39)
GPU: Intel UHD 770
OS: Fedora 35
Kernel: 5.16.8 
Mesa: 21.3.6
Test program: [Vulkan-sample's triangle](https://github.com/KhronosGroup/Vulkan-Samples)

### Notes and Thoughts
Intel UHD 770's supported DRM suported modifiers are both linear tiling ([fourcc.h](https://github.com/torvalds/linux/blob/b81b1829e7e39f6cebdf6e4d5484eacbceda8554/include/uapi/drm/drm_fourcc.h#L477)). I think it could returns rowpitch > 0, but `vkGetImageSubresourceLayout` returns no row pitch in some implementations (cf. [vkGetImageSubresourceLayout gives no row pitch](https://forums.developer.nvidia.com/t/vkgetimagesubresourcelayout-gives-no-row-pitch/42067)). I don't know the issue is whether a driver's bug or not.

GL capture works without any problem. The issue is only for Vulkan capture.

**Comment by nowrep** [comment]
What about this patch

```diff
diff --git a/src/vklayer.c b/src/vklayer.c
index 5f289e0..1b8c089 100644
--- a/src/vklayer.c
+++ b/src/vklayer.c
@@ -786,7 +786,7 @@ static inline bool vk_shtex_init_vulkan_tex(struct vk_data *data,
         VkImageSubresource sbr = {};
         sbr.mipLevel = 0;
         sbr.arrayLayer = 0;
-        sbr.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
+        sbr.aspectMask = VK_IMAGE_ASPECT_PLANE_0_BIT;
         VkSubresourceLayout layout;
         funcs->GetImageSubresourceLayout(device, swap->export_image, &sbr, &layout);
 
```

**Comment by nm004** [comment]
Wow, it works like magic! Thank you :)
