### ISSUE TITLE
AUR package needs update

### ISSUE THREAD

**Issue by plasticbomb1986** [nowrep/obs-vkcapture#61]
When i wanna update the aur package on my install it keep failing with:

`CMake Error at CMakeLists.txt:44 (find_package):
  By not providing "FindLibObs.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "LibObs", but
  CMake did not find one.

  Could not find a package configuration file provided by "LibObs" with any
  of the following names:

    LibObsConfig.cmake
    libobs-config.cmake

  Add the installation prefix of "LibObs" to CMAKE_PREFIX_PATH or set
  "LibObs_DIR" to a directory containing one of the above files.  If "LibObs"
  provides a separate development package or SDK, be sure it has been
  installed.
`
Same with building from here right away. Checking obs gits they do not provide the FindLibObs.cmake anymore, but refer to an updated wiki to check it how to.

**Comment by nowrep** [comment]
That's not true, they still provide LibObs package: https://github.com/obsproject/obs-studio/blob/master/libobs/LibObsConfig.cmake.in

**Comment by gmarxcc** [comment]
same error here 
```
CMake Error at CMakeLists.txt:22 (find_package):
  By not providing "FindLibObs.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "LibObs", but
  CMake did not find one.

  Could not find a package configuration file provided by "LibObs" with any
  of the following names:

    LibObsConfig.cmake
    libobs-config.cmake

  Add the installation prefix of "LibObs" to CMAKE_PREFIX_PATH or set
  "LibObs_DIR" to a directory containing one of the above files.  If "LibObs"
  provides a separate development package or SDK, be sure it has been
  installed.
```

**Comment by plasticbomb1986** [comment]
> It build just fine in chroot.
> 
> The only thing I can think of that could be an issue if you use some unofficial obs-studio package from aur, but it works fine with the one in arch repo. Also, if you want to get help, make sure to post the full build log...

You are right, its the obs-studio-git package from aur.

**Comment by 8andage** [comment]
The git version of OBS doesn't make the required folder in /usr/lib/cmake/LibObs. Copying this folder from regular OBS makes the installation of vkcapture work
