### ISSUE TITLE
Game Capture won't appear in sources

### ISSUE THREAD

**Issue by QushyQushy** [nowrep/obs-vkcapture#62]
Hello, I'm on Fedora 36 Beta with Plasma as the DE. I downloaded the project, built it and installed it. I lanched OBS with `OBS_USE_EGL=1 obs` but the Game Capture source doesn't appear anywhere. Am I missing something?
Also downloaded the Flatpak OBS and VKCapture, there the source appears but it won't capture anything, potentially cause Steam is a repo package and not he Flatpak.

**Comment by nowrep** [comment]
If you build it from source make sure the install prefix is correct (you can check where other obs plugins are installed from the obs fedora package)

**Comment by QushyQushy** [comment]
> If you build it from source make sure the install prefix is correct (you can check where other obs plugins are installed from the obs fedora package)

It was indeed in lib64 and not lib. It seems ot detect the plugin now thanks! :)

**Comment by QushyQushy** [comment]
Ok, I still have the same issue that it doesn't seem to be able to capture the game even wirh OBS from the repos. Should I open anohter issue?

**Comment by nowrep** [comment]
Yes please. Also make sure to attach terminal output from the game you are trying to run and from obs too.
