### ISSUE TITLE
Fails to capture game Witcher 2 Proton+dxvk

### ISSUE THREAD

**Issue by Lepidos** [nowrep/obs-vkcapture#64]
I don't have anymore DX9 games to test. Don't know if that could be related.

**Comment by nowrep** [comment]
Can you please post logs from obs and from the game?

**Comment by Lepidos** [comment]
[steam-log.txt](https://github.com/nowrep/obs-vkcapture/files/8501209/steam-log.txt)

**Comment by nowrep** [comment]
Please post log from obs (run it from terminal).

**Comment by Lepidos** [comment]
[obs-log.txt](https://github.com/nowrep/obs-vkcapture/files/8501263/obs-log.txt)

**Comment by nowrep** [comment]
Are you sure it is using dxvk? I don't see anything about it in the log. In that case, try with `obs-glcapture`.

**Comment by Lepidos** [comment]
yes I'm sure
![witcher](https://user-images.githubusercontent.com/51986094/163709949-7ef59b3d-1788-42f9-b477-a6239538da88.png)

**Comment by nowrep** [comment]
It doesn't look like it from the log. Also checking protondb this game doesn't seem to be using dxvk by default, have you manually enabled it?

**Comment by Lepidos** [comment]
yes I have checked the box ``use compatibility tool``

**Comment by Lepidos** [comment]
Maybe it's related to the game being DX9. Because couldn't capture _Papo & Yo_. Or maybe because is 32-bit app??

**Comment by nowrep** [comment]
Actually did you post output of a `steam` command? It has to be log from the game: add `PROTON_LOG=1 %command%` to your launch command and then it will be in your home directory as `steam-xxx.log`

**Comment by Lepidos** [comment]
[steam-20920.log](https://github.com/nowrep/obs-vkcapture/files/8501460/steam-20920.log)
Yes I did, here's what you requested

**Comment by nowrep** [comment]
The log still doesn't show that the game actually uses Vulkan, have you tried running with `obs-glcapture`?

**Comment by Lepidos** [comment]
On the screenshot https://user-images.githubusercontent.com/51986094/163709949-7ef59b3d-1788-42f9-b477-a6239538da88.png you can see DXVK_HUD=gpuload

**Comment by Lepidos** [comment]
@nowrep Does 32-bit games need to obs-vkcapture be compiled on 32-bit OS?

**Comment by nowrep** [comment]
Yes, you will need 32bit build for 32bit games.

**Comment by Lepidos** [comment]
Ok, Thanks And I'm sorry. for the trouble 
I will try to compile on chroot environment
