### ISSUE TITLE
Cannot build obs-vkcapture from source on Ubuntu-based distro!

### ISSUE THREAD

**Issue by pantsuteam** [nowrep/obs-vkcapture#69]
Whenever i start to make the build , it's always come to this
```css
pftm@pftm-PC:~$ cd /home/pftm/obs-vkcapture/build
pftm@pftm-PC:~/obs-vkcapture/build$ make
[ 30%] Built target VkLayer_obs_vkcapture
[ 80%] Built target obs_glcapture
[ 90%] Building C object CMakeFiles/linux-vkcapture.dir/src/vkcapture.c.o
/home/pftm/obs-vkcapture/src/vkcapture.c:22:10: fatal error: obs-nix-platform.h: No such file or directory
   22 | #include <obs-nix-platform.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/linux-vkcapture.dir/build.make:63: CMakeFiles/linux-vkcapture.dir/src/vkcapture.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:134: CMakeFiles/linux-vkcapture.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
pftm@pftm-PC:~/obs-vkcapture/build$ 
```

where can i find "obs-nix-plaform.h"?
![image](https://user-images.githubusercontent.com/19551146/168814660-949c09fe-e947-4011-a056-049f58985d35.png)

**Comment by nowrep** [comment]
What version of OBS are you trying to build against?

**Comment by pftmclub** [comment]
> What version of OBS are you trying to build against?

OBS v27.2.4 from Flathub

**Comment by nowrep** [comment]
You can't build it against flatpak installation. It has to be installd system-wide.

**Comment by pftmclub** [comment]
> You can't build it against flatpak installation. It has to be installd system-wide. But also, if you use OBS from flatpak you will need to use obs-vkcapture from flatpak too. And in that case, you only need to build the capture tools: `cmake -DBUILD_PLUGIN=OFF`

Hello i try to install OBS from official repo, and then i build obs-vkcapture successfuly , but nothing in OBS showing up
```css
pftm@pftm-PC:~$ cd /home/pftm/obs-vkcapture/build
pftm@pftm-PC:~/obs-vkcapture/build$ make
-- Checking for module 'xcb-xfixes'
--   No package 'xcb-xfixes' found
-- Checking for module 'wayland-client'
--   No package 'wayland-client' found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pftm/obs-vkcapture/build
[ 30%] Built target VkLayer_obs_vkcapture
[ 80%] Built target obs_glcapture
[ 90%] Building C object CMakeFiles/linux-vkcapture.dir/src/vkcapture.c.o
[100%] Linking C shared module linux-vkcapture.so
[100%] Built target linux-vkcapture
```
![image](https://user-images.githubusercontent.com/19551146/169044136-58aec720-e1d7-4c6a-bad7-1ff2def53004.png)

check the video, the VK Capture is missing!
https://user-images.githubusercontent.com/19551146/169045369-25f0f7a3-2341-4013-9e55-16856defab6f.mp4

**Comment by nowrep** [comment]
For ubuntu the libdir would be lib/x86_64-linux-gnu: `cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib/x86_64-linux-gnu`
