### ISSUE TITLE
Build deps not specified in repo.

### ISSUE THREAD

**Issue by NotStepbro** [nowrep/obs-vkcapture#78]
Hi, No dependencies are listed in the repo. This makes compiling annoying as you must find the deps one at a time from the cmake errors.

On Fedora, The dependencies were
cmake
make
gcc-g++
obs-studio-devel
wayland-devel
mesa-libGL-devel
vulkan-devel
vulkan-loader-devel

**Comment by nowrep** [comment]
Patches welcome.

The dependencies are pretty much all what you expect - it captures OpenGL and Vulkan applications so it needs OpenGL and Vulkan libs, it's also OBS plugin so it needs OBS libs. Wayland/X11 is optional.

There is also PKGBUILD that you can look at for Arch deps.
