### ISSUE TITLE
Issue consistently capturing MangoHud

### ISSUE THREAD

**Issue by GloriousEggroll** [nowrep/obs-vkcapture#81]
In DOOM Eternal if I enable MangoHud and use obs-vkcapture to capture the game, sometimes (frequently) between loading screens obs-vkcapture will stop capturing mangohud. The hud still stays on on my actual screen but it disappears from the capture. Video sample attached.

https://youtu.be/DDIXR3ojpRQ

**Comment by nowrep** [comment]
Can you post logs from the game? Do you use explicit layer config (see #14) to force layer loading order?

**Comment by GloriousEggroll** [comment]
Unfortunately I tried multiple variations and just could not get mangohud to stick.

> Moved:
obs_vkcapture_32.json  obs_vkcapture_64.json MangoHud.json from /usr/share/vulkan/implicit_layer.d to /usr/share/vulkan/explicit_layer.d

> Disabled steam overlay.

(1) Tried:
VK_INSTANCE_LAYERS=VK_LAYER_MANGOHUD_overlay:VK_LAYER_OBS_vkcapture_64:VK_LAYER_OBS_vkcapture_32 OBS_VKCAPTURE=1 mangohud %command%

mangohud stops being captured at the intro logo/main menu

(2) Tried:
VK_INSTANCE_LAYERS=VK_LAYER_OBS_vkcapture_64:VK_LAYER_OBS_vkcapture_32:VK_LAYER_MANGOHUD_overlay OBS_VKCAPTURE=1 mangohud %command%

mangohud never captures

(3) Tried:
VK_INSTANCE_LAYERS=VK_LAYER_MANGOHUD_overlay:VK_LAYER_OBS_vkcapture_64 OBS_VKCAPTURE=1 mangohud %command%

Same problem as (1)

(4) Tried:
VK_INSTANCE_LAYERS=VK_LAYER_OBS_vkcapture_64:VK_LAYER_MANGOHUD_overlay OBS_VKCAPTURE=1 mangohud %command%

Same problem as (2)

**Comment by GloriousEggroll** [comment]
thanks, just tested, working great!
