### ISSUE TITLE
obs-vkcapture for Origin games

### ISSUE THREAD

**Issue by jarrard** [nowrep/obs-vkcapture#82]
Seems there could be a problem running obs-vkcapture with origin games as they run behind a Origin launcher which does not at all like obs-vkcapture run before it.

It be nice if there was a env variable that could be used like OBSCAPTURE = "Game.exe"   ? something like that would be useful.

EDIT: It might just be a issue with the quicklaunch method. Running obs-vkcapture on origin.exe appears to work, maybe.  

EDIT2: Nope, seems it will ignore anything launched with origin. Except launchers itself...
Using Mass Effect LEG as a test case, it can't see the game exe in the game capture source.

**Comment by nowrep** [comment]
You're only supposed to run the games with obs-vkcapture, not launchers (same with Steam).

But please post logs and describe the issue better. It just doesn't show in OBS in game list, it crashes the game, etc?

**Comment by jarrard** [comment]
Some games are forced to run through launcher. No method around it unfortunately. 
MEL123 for example has a launcher you must go through afaik.  But its not a big issue at end of day, just a limitation of this tool I guess.

**Comment by nowrep** [comment]
I would still like to see the logs from the game where it doesn't work.
Also logs with `VK_LOADER_DEBUG=all` env variable set.

**Comment by jarrard** [comment]
Well it does work but it ONLY detects the Origin.exe and MELauncher.exe files. Selecting the pick any window option doesn't solve the issue. 

So basically its run like obs-vkcapture Origin.exe since that is what you need to do. Now maybe other games work that don't have launchers but afaik games that have a forced launcher like Mass Effect are causing a issue for game detection.

I'll work on getting those logs for you non the less.

**Comment by nowrep** [comment]
As long as it doesn't crash the game/launcher it doesn't really matter if the obs-vkcapture gets loaded into launcher process too. It should show the launcher AND the game in the "select window" option in OBS.
But yes, please try to get the logs.

**Comment by jarrard** [comment]
Here is a log capture.  Bit messy but you can see vkcapture is logging correctly there.

Basically it sees Origin.exe MassEffectLauncher but not the game behind those.

**Comment by jarrard** [comment]
Out of curriosity I disabled gamemoderun, vkbasalt, and mangohud (using environmental flags and options in lutris).
Now when I go to the game main menu and minimize back to OBS, it appears! 
I've used those things before without issue. Odd. Maybe this isn't a problem after-all? 

[obscapturevkloader-logs-2.log](https://github.com/nowrep/obs-vkcapture/files/9286281/obscapturevkloader-logs-2.log)

**Comment by nowrep** [comment]
Can you build obs-vkcapture in debug and get the logs again? Also without the VK_LOADER_DEBUG (the layer gets loaded correctly in both cases).

**Comment by jarrard** [comment]
Sorry I've changed my setup and it will be a while before I test any origin stuff again. (data lost)
Did a complete whip and now trying to move to flatpak steam...

**Comment by nowrep** [comment]
Please reopen if you still have this issue.
