### ISSUE TITLE
Obs don't capture mangohud on Nobara 36 kde

### ISSUE THREAD

**Issue by tuxtergames** [nowrep/obs-vkcapture#84]
Hi!

I just spend a few days trying to capture mangohud with OBS here using vk-capture without success, I'm using Fedora nobara 36 kde, and follow instructions acording communit.
I'm using X11 then I run here "OBS_USE_EGL=1 vk_pro obs" in OBS everything seems run fine, but in game-gapture menu, don't show mangohud, if I try to capture full windows works, acording some posts I launch my game with "VK_LOADER_DEBUG=all" to debug log, I just run steam with this "vk_radv obs-gamecapture mangohud %command%"
and I try this too, 
"VK_INSTANCE_LAYERS=VK_LAYER_MANGOHUD_overlay:VK_LAYER_OBS_vkcapture_64:VK_LAYER_OBS_vkcapture_32 OBS_VKCAPTURE=1 mangohud %command%" 
but nothing works, I'll apreciatte some help here, If theres a different way to get other logs please help to get here.
I using a AMD rx 5600
![Screenshot_20220808_092416](https://user-images.githubusercontent.com/26095484/183417326-67ec8058-018a-48b9-99df-207094ebd55a.png)

log attached

[avengers steam-997070.log](https://github.com/nowrep/obs-vkcapture/files/9281706/avengers.steam-997070.log)
[grid 2019 steam-703860.log](https://github.com/nowrep/obs-vkcapture/files/9281708/grid.2019.steam-703860.log)
[mudrunner steam-675010.log](https://github.com/nowrep/obs-vkcapture/files/9281709/mudrunner.steam-675010.log)

**Comment by nowrep** [comment]
It would be

    VK_INSTANCE_LAYERS=VK_LAYER_MANGOHUD_overlay:VK_LAYER_OBS_vkcapture_64:VK_LAYER_OBS_vkcapture_32 %command%

but you also need to copy the layer files from `/usr/share/vulkan/implicit_layer.d` to `/usr/share/vulkan/explicit_layer.d`

**Comment by tuxtergames** [comment]
> It would be
> 
> ```
> VK_INSTANCE_LAYERS=VK_LAYER_MANGOHUD_overlay:VK_LAYER_OBS_vkcapture_64:VK_LAYER_OBS_vkcapture_32 %command%
> ```
> 
> but you also need to copy the layer files from `/usr/share/vulkan/implicit_layer.d` to `/usr/share/vulkan/explicit_layer.d`

Tks a lot man, one week spend trying to fix it, works now! 
you can close here.....
