### ISSUE TITLE
Game Capture show up but doesnt let me select any window 

### ISSUE THREAD

**Issue by AmyRoxwell** [nowrep/obs-vkcapture#88]
Os: Pop_OS 22.04 X11
I have install Obs-vkcapture and set up everything to make it work (like putting the env var "OBS_USE_EGL=1" into the OBS flatpak using flatseal), game capture show up but after click on it doesnt let select a window to stream, what can I do to fix it? 

![Screenshot from 2022-08-24 16-23-06](https://user-images.githubusercontent.com/89411895/186526232-ca9ccbeb-f3ca-483d-b8be-f4a3d5594f6e.png)

**Comment by nowrep** [comment]
Please post logs from both OBS and the game.

**Comment by AmyRoxwell** [comment]
Obs log:
[2022-08-25 13-01-24.txt](https://github.com/nowrep/obs-vkcapture/files/9427239/2022-08-25.13-01-24.txt)
Game log? I dont know how to do that but the game is ultrakill

**Comment by nowrep** [comment]
If you play it on steam, change the startup command to `PROTON_LOG=1 obs-gamecapture %command%` and the log will be in your home directory.

**Comment by AmyRoxwell** [comment]
Well, I tried the startup command but the game refuses to start if "obs-gamecapture" is included, if I put just PROTON_LOG=1 then the game starts just fine

**Comment by nowrep** [comment]
Try `PROTON_LOG=1 OBS_VKCAPTURE=1 %command%`

**Comment by AmyRoxwell** [comment]
It actually start without issue with the new command!
Here is the log file for the game: 
[steam-1229490.log](https://github.com/nowrep/obs-vkcapture/files/9433748/steam-1229490.log)

**Comment by nowrep** [comment]
It doesn't seem to load the vkcapture layer. Can you post log with `PROTON_LOG=1 VK_LOADER_DEBUG=all %command%`?

**Comment by Alberto-vgdd** [comment]
Hi, I am having the same exact issue as AmyRoxwell. Whenever I try launching a game using `obs-gamecapture %command%` the application doesn't launch at all. I just tried launching Elden Ring using `PROTON_LOG=1 VK_LOADER_DEBUG=all %command%` and it opened a white screen (I believe the game froze) and spit this log.
[steam-1245620.log](https://github.com/nowrep/obs-vkcapture/files/9468914/steam-1245620.log)

I am using EndeavourOS (arch based) with a Ryzen 7 3700x and a Radeon RX 6700 XT

**Comment by nowrep** [comment]
Sorry, the command needs to be `PROTON_LOG=1 OBS_VKCAPTURE=1 VK_LOADER_DEBUG=all %command%`. Can you please run it again?

**Comment by Alberto-vgdd** [comment]
Sure, I just tried that new launch command on DOOM Eternal instead, as Elden Ring's white screen seems to be a different issue.
[steam-782330.log](https://github.com/nowrep/obs-vkcapture/files/9469035/steam-782330.log)

**Comment by nowrep** [comment]
The layer is either installed in the wrong directory or Steam pressure-vessel doesn't pick it up for some reason.
Does it work with native applications? `obs-gamecapture vkcube`.
Is the layer available in vulkaninfo? `vulkaninfo | grep VK_LAYER_OBS_vkcapture`

**Comment by Alberto-vgdd** [comment]
This might be it. My computer does not recognize `obs-gamecapture`. I did install it through flatpak following the readme.md. Is there an extra step to "expose" the program to my computer that I missed?
![image](https://user-images.githubusercontent.com/22345650/187897327-ee7304ec-ce9e-42fb-8451-65bbbd34cc63.png)

**Comment by nowrep** [comment]
Flatpak only works if you use Steam flatpak too. Otherwise you need to build obs-vkcapture native.

**Comment by nowrep** [comment]
I added note about Flatpak in README.
