### ISSUE TITLE
X11/OpenBox: Stream crash when game is in separate virtual Desktop

### ISSUE THREAD

**Issue by AdelKS** [nowrep/obs-vkcapture#9]
Hello,

I must say that this plugin is a godsend with respect to added input lag. Unfortunately I cannot use it yet to stream: I use LXQt (because it does not have a compositor with OpenBox) and put the game in a separate virtual desktop. I sometimes switch on and off the game. And when using `game capture` the twitch stream directly crashes. Please see the attached video.

Can you reproduce the error ? Using Xcomposite does not produce this error afaik, I tested it for a few minutes and it didn't get triggered. 

I have `obs-studio` and `obs-vkcapture` compiled from Git. I use Gentoo, with `mesa/radv 21.1.0_rc3` to run my games on my RX 5700 XT and to stream with FFMPEG-VAAPI with the GPU.

Thanks!

[OBS Stream crash.zip](https://github.com/nowrep/obs-vkcapture/files/6424426/OBS.Stream.crash.zip)

**Comment by nowrep** [comment]
Can you please send terminal output of OBS and, if possible, also Overwatch.
Also, does it happen with all games, or only Overwatch? You can try it with eg. `vkcube`.

**Comment by AdelKS** [comment]
I couldn't find a way to make `vkcube` to run in fullscren... I found no documentation whatsoever.

And when I tried to run `obs-studio` again to get the output terminal output, it didn't want to work anymore... This is very frustrating. I will try again.

![screenshot-73349b0c](https://user-images.githubusercontent.com/13605217/117226893-edacc080-ae15-11eb-89be-003bf86e26c8.jpg)

**Comment by nowrep** [comment]
So does it happen only when streaming or will the preview in obs (without streaming) go black after switching virtual desktops too?
Because if it only happens when streaming, the issue will probably be somewhere else.

**Comment by AdelKS** [comment]
The fact that the preview goes black when switching desktops is not related to streaming or not: any full screen application is not rendered anymore till it gets back focus. So the game stops rendering. `vk-capture` seems to give out a gray background when that happens.

I think the issue is that `game capture` doesn't give proper frames to the encoder when the virtual desktop switching happens, (from showing a game, to nothing to show) so it makes buggy frames or something ? I can still record (without streaming) and playing the recording even if I switch virtual desktops. Previewing the recording shows a gray background with some kind of weird stutters when I switch off the game. I think that is the root cause of crashing the stream since twitch expects some proper frames or something

I couldn't test vkcube because I could not run it in fullscreen, in windowed, it is always rendered and therefore has a preview at all times

The difference between `game capture` and `xcomposite` with regards to virtual desktop switching is that `xcomposite` keeps a black frame when the switch happens, and the preview keeps the original size of the previewed "window". `vk-capture` in the other hand makes the preview bounds back to a null square. Touching that square makes the capture not work anymore.

Please find attached a screen recording of some manipulations I do to showcase the issues at hand, along with a recording of what the "stream" would be (without streaming, I just recorded on the disk).

Thank you for your help!

[vk-capture.zip](https://github.com/nowrep/obs-vkcapture/files/6435086/vk-capture.zip)
[screen-capture.zip](https://github.com/nowrep/obs-vkcapture/files/6435087/screen-capture.zip)

**Comment by nowrep** [comment]
No, that's most likely not the issue. There are no "buggy frames" or anything like that (and if, it's certainly not because of the game capture source).
OBS takes the entire scene as a frame for encoder, so it doesn't matter if the scene is empty - it will still produce valid frames/video.
The capture is fine, there is no reason for it to "crash" the stream. You can try streaming empty scene and you'll see it works.

I don't really see a reason to provide some placeholder width/height when the texture is invalid. It won't help with anything, quite the opposite - it may try to read invalid image data.

Also, I asked for a logs from overwatch/obs, can you please post them? Because that grey flickering looks like it is picking up some other swapchain that renders this grey empty image? Or this is just what the game renders in that "blocked rendering" state. That is the only explanation how would that image got into recording.

**Comment by AdelKS** [comment]
Got it! What seems to be sure is that switching between virtual desktops triggers the issue. If I stay on Overwatch and never leave the game, everything would be fine.

> No, that's most likely not the issue. There are no "buggy frames" or anything like that (and if, it's certainly not because of the game capture source).

The video I recorded on my disk looks exactly like what's sent to Twitch. The difference is that the local video plays normally on my machine and shows those switches between gray background and the game without blocking. On Twitch, doing that makes the stream unplayable on a browser nor on the phone app, it may be a twitch quirk. Actually I did get a similar issue with `Xcomposite` capture in the past: I opened [an issue](https://github.com/obsproject/obs-studio/issues/3719) about it, with a [video capture](https://www.youtube.com/watch?v=muPDcvfx6vE) to showcase it. It seems to mostly work lately now.

> I don't really see a reason to provide some placeholder width/height when the texture is invalid. It won't help with anything, quite the opposite - it may try to read invalid image data.

Actually this is another issue: as of now, there is no way to resize the capture to make it fit in the scene in a way the user wants: it can only have the resolution of the captured content. Giving a place holder enables resizing.

Please find attached OBS logs, I will run Overwatch again to attach whatever wine outputs, I have the gut feeling this is not specific to overwatch although I do not have any other game installed : do you have some full screen vulkan demo/game in mind I could test ? vkcube afaik cannot run in fullscreen.

[2021-05-06 15-46-18.txt](https://github.com/nowrep/obs-vkcapture/files/6435629/2021-05-06.15-46-18.txt)
[2021-05-06 15-40-20.txt](https://github.com/nowrep/obs-vkcapture/files/6435630/2021-05-06.15-40-20.txt)

**Comment by AdelKS** [comment]
> I think you can resize even when is it in that 1x1 state and OBS will remember this size.

Yes it does, although the game is not captured properly anymore, partly because the aspect ratio is not the same, please have a look at the videos attached two messages ago.

**Comment by AdelKS** [comment]
Thanks! Hopefully this change will solve my issue, I will test it later and report back.

**Comment by nowrep** [comment]
It should fix the grey frames.
If you still have issues with the stream ending, then that is outside of the scope of this plugin however.

**Comment by AdelKS** [comment]
> It should fix the grey frames.

Yes, and hopefully it will enable resizing :D

> If you still have issues with the stream ending, then that is outside of the scope of this plugin however.

I understand, thank you for the time you have given for this issue so far. I believe stopping those flickers will help out with my streaming issues. If the issue remains I will just stop using virtual desktops.

**Comment by AdelKS** [comment]
I've been streaming for more than an hour and it's going alright! So that change did indeed also my stream problems as I guessed. Thanks!
