### ISSUE TITLE
Not working in 28.0-rc2

### ISSUE THREAD

**Issue by 3laws** [nowrep/obs-vkcapture#90]
Is the flatpak version compatible yet? Maybe I'm ahead of myself here.

Fedora 36. Flatpak OBS. Can't speak for the RPM since I have not been able to build from source for Fedora.

**Comment by nowrep** [comment]
No idea about flatpak, but the native build works just fine with 28.0 / `master`.
@SuNNjek ^

**Comment by SuNNjek** [comment]
@3laws It's only being built for the flatpak stable branch atm. This is not a compatibility issue, other plugins that aren't built for beta (which is almost all of them) also don't show up in the beta branch, that's unfortunately how flatpak works. Is there any reason you need the beta branch specifically?

**Comment by SuNNjek** [comment]
I've added a beta branch in the flatpak repo now. It should be available in a few hours. You need to then install the plugin again for the beta branch: `flatpak install flathub-beta com.obsproject.Studio.Plugin.OBSVkCapture`

**Comment by SuNNjek** [comment]
Beta build has now been published and works (at least on my machine 😋)
![Screenshot_20220830_225358](https://user-images.githubusercontent.com/20151081/187541781-8c700a3f-0843-4ee8-b6a7-afa3835b74c7.png)

**Comment by 3laws** [comment]
> I've added a beta branch in the flatpak repo now. It should be available in a few hours. You need to then install the plugin again for the beta branch: `flatpak install flathub-beta com.obsproject.Studio.Plugin.OBSVkCapture`

Yep, this is what it needed. Snce I don't fiddle with Flatpak that much I wasn't sure if the `beta` branch meant that only other packages within the branch worked with each other. Is this a correct assumption?

If so, to keep an eye on the other plugins that I use. I'm using this branch cuz I haven't been able to build from source since forever and the master branch of OBS had a bug that was never resolve for me (I never opened a github issue since one maintainer pretty much confirmed they were not fixing it until next release on Twitte) Thanks a lot @SuNNjek 

@nowrep out of curiosity, I know you work on native, do you mean Ubuntu? or do you build from source for another Debian distro? We've had some back and forth with issues on my end since I'm in Fedora.

**Comment by nowrep** [comment]
I am on Arch Linux. I tried it with custom build and also with obs-studio-git from AUR.

**Comment by SuNNjek** [comment]
> Yep, this is what it needed. Snce I don't fiddle with Flatpak that much I wasn't sure if the `beta` branch meant that only other packages within the branch worked with each other. Is this a correct assumption?

Yes, since the VkCapture flatpak is an extension for another flatpak (OBS), the branches need to match. This goes for any other OBS plugins as well
