### ISSUE TITLE
Steam UI not working when under obs-vkcapture

### ISSUE THREAD

**Issue by Lepidos** [nowrep/obs-vkcapture#91]
version 1.2.0
tried:
``obs-gamecapture steam`` and
``obs-vkcapture steam``
the result:
![20220901_23h11m11s_grim](https://user-images.githubusercontent.com/51986094/188022477-784979c6-bee6-465c-9c5a-c51fa7f566ca.png)

**Comment by nowrep** [comment]
You're not supposed to use it on Steam itself, rather just on the games by setting it in custom game launch command.
In any case, I will add blacklist (same as what MangoHud is doing) and that should fix it.

**Comment by nowrep** [comment]
Or you can just use `OBS_VKCAPTURE=1 steam`. It's always just the GL hook that is breaking things.

**Comment by Lepidos** [comment]
thank you
