### ISSUE TITLE
Possible install location issue for OBS 28 with Ubuntu

### ISSUE THREAD

**Issue by FireStarW** [nowrep/obs-vkcapture#93]
Running Ubuntu 22.04, using the stable PPA (https://launchpad.net/~obsproject/+archive/ubuntu/obs-studio/+packages) version of OBS 28, I couldn't get the game capture plugin to appear in OBS by following the build instructions in the readme, despite it working fine in obs 27.

Taking a look at what the OBS 28 *.deb includes, I noticed it installs the built in plugins to:
`/usr/lib/x86_64-linux-gnu/obs-plugins/`

The make file from this project installs to:
`/usr/lib/obs-plugins/`

I moved the plugin to the `/usr/lib/x86_64-linux-gnu/obs-plugins/` directory and it then loaded into OBS.

Since someone else left an issue to state it worked fine with them on OBS 28, I'm guessing this may be a specific quirk with the Ubuntu PPA version of OBS, where the readme's instructions do not work for install.

**Comment by gabriele2000** [comment]
> Running Ubuntu 22.04, using the stable PPA (https://launchpad.net/~obsproject/+archive/ubuntu/obs-studio/+packages) version of OBS 28, I couldn't get the game capture plugin to appear in OBS by following the build instructions in the readme, despite it working fine in obs 27.
> 
> Taking a look at what the OBS 28 *.deb includes, I noticed it installs the built in plugins to: `/usr/lib/x86_64-linux-gnu/obs-plugins/`
> 
> The make file from this project installs to: `/usr/lib/obs-plugins/`
> 
> I moved the plugin to the `/usr/lib/x86_64-linux-gnu/obs-plugins/` directory and it then loaded into OBS.
> 
> Since someone else left an issue to state it worked fine with them on OBS 28, I'm guessing this may be a specific quirk with the Ubuntu PPA version of OBS, where the readme's instructions do not work for install.

Yeah that was me.
Since OBS 27, running Pop!_Os (an ubuntu-based distro), I set a cmake variable to point to `/usr/lib/x86_86-linux-gnu` because that's different from... arch for example?
