### ISSUE TITLE
Fedora 36 dependencies

### ISSUE THREAD

**Issue by mohsunb** [nowrep/obs-vkcapture#95]
I have spent a few hours trying all kinds of dependencies on Fedora 36 Workstation trying to get this to compile. I have found the exact ones and hopefully it helps someone in the future: 
* ```cmake```
* ```gcc```
* ```gcc-c++```
* ```obs-studio-devel```
* ```mesa-libGL-devel```
* ```vulkan-loader-devel```

Here is a convenient command to install all at once:
```
sudo dnf install cmake gcc gcc-c++ obs-studio-devel mesa-libGL-devel vulkan-loader-devel
```

**Comment by jn64** [comment]
Duplicate of #78

**Comment by mohsunb** [comment]
I am sorry for the clutter I caused. Unfortunately, title of issue #78 was not related to Fedora so I must have missed it when I glanced over closed issues.
