### ISSUE TITLE
Plugin isn't recognizing that EGL is enabled.

### ISSUE THREAD

**Issue by nambona890** [nowrep/obs-vkcapture#96]
I built this with the intention of being able to properly capture games like Judgment, which lag horribly when using regular Window Capture.
I run Nobara KDE 36, which is a Fedora-based distro.
At first when I opened OBS after installing it, there was no Game Capture option, so I checked the logs, and saw "linux-vkcapture cannot run on non-EGL platforms".
So I looked it up, and found that you have to use OBS_USE_EGL=1 to work around the issue.
Problem is, even when I set that environment variable, I still get the same error. Even though earlier in the log, it literally says that it's using EGL and has successfully initialized it.
Am I missing something?

**Comment by nowrep** [comment]
Post full OBS log please.

**Comment by nambona890** [comment]
https://pastebin.com/xJUKhA53

**Comment by nambona890** [comment]
> Post full OBS log please.

https://pastebin.com/xJUKhA53

**Comment by nowrep** [comment]
You probably built it without wayland libs, and because of OBS_NIX_PLATFORM_WAYLAND only being defined when wayland is enabled it won't work.

You don't need OBS_USE_EGL on OBS 28.0, it's now enabled by default (and there is no GLX support anymore).
Nobara have this plugin in repositories, which you should use instead.

**Comment by nambona890** [comment]
This did end up solving the issue. Thank you so much. I was confused as to why it was acting this way despite it successfully building.

**Comment by YellowOnion** [comment]
The plugin was working a few days ago and now I get this error, I'm still on 27.2, I don't really understand what has changed.

Here's a log file: https://obsproject.com/logs/V05ibv2wyfWFS_XY

**Comment by nowrep** [comment]
Did you build it with Wayland libraries?
Also you have a lot of duplicate plugins, so I'm not really sure what have you done with your installation.

**Comment by YellowOnion** [comment]
@nowrep okay that solved it, it's been working for months without them.

The duplicates are just a quirk of NixOS using symlinks to put the libraries in the LD path, and OBS looking for plugins in multiple locations. I'm not the maintainer of OBS package, it's probably fixable, but I wouldn't think it's all that much of an issue.
