### ISSUE TITLE
Native OBS capture Flatpak Steam Games.

### ISSUE THREAD

**Issue by jarrard** [nowrep/obs-vkcapture#97]
Just wondering how this is done.  I can't use the flatpak OBS as it does not have a build for AMF encoders nor all plugin support.

It seems obs-vkcapture enable in flatpak steam doesn't pass outside to native OBS builds?

**Comment by nowrep** [comment]
You need to install native plugin, it's in README.

**Comment by jarrard** [comment]
Yeah I have that. Doesn't appear to work however.

**Comment by nowrep** [comment]
I don't use flatpak, but as far as I understand it should work both ways.
@SuNNjek Any ideas?

**Comment by SuNNjek** [comment]
@jarrard It might be that you have the wrong version of the capture tools installed. Steam recently upgraded their runtime to 22.08 and unfortunately that means that you need to install the capture tools for that runtime (same goes for vkBasalt btw). See also this: https://github.com/flathub/org.freedesktop.Platform.VulkanLayer.OBSVkCapture/issues/13#issuecomment-1236180531

**Comment by jarrard** [comment]
Yep that seems to have fixed it. VkBasalt however only has STABLE flatpak option so I dunno what version that is...

**Comment by SuNNjek** [comment]
@jarrard Great. Weird that vkBasalt doesn't show up for you, on my system I get the following output:
```
Similar refs found for ‘org.freedesktop.Platform.VulkanLayer.vkBasalt’ in remote ‘flathub’ (system):

   1) runtime/org.freedesktop.Platform.VulkanLayer.vkBasalt/x86_64/21.08
   2) runtime/org.freedesktop.Platform.VulkanLayer.vkBasalt/x86_64/22.08
   3) runtime/org.freedesktop.Platform.VulkanLayer.vkBasalt/x86_64/stable

Which do you want to use (0 to abort)? [0-3]:
```

The command to install it would be `flatpak install org.freedesktop.Platform.VulkanLayer.vkBasalt`

**Comment by jarrard** [comment]
I was using   com.valvesoftware.Steam.Utility.vkBasalt  :(
